<?php
/**
 * Hungarian texts
 *
 * phpGedView: Genealogy Viewer
 * Copyright (C) 2002 to 2008  PGV Development Team.  All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *
 * @author PGV Developers
 * @author Hrotkó Gábor <roti@al.pmmf.hu>
 * @package PhpGedView
 * @subpackage Languages
 * @version $Id$
 */

if (!defined('PGV_PHPGEDVIEW')) {
	header('HTTP/1.0 403 Forbidden');
	exit;
}

//-- GENERAL
$pgv_lang["help_header"]			= "Általános tudnivalók:";
$pgv_lang["privacy_error_help"]			= "Ön számos eltérő okból olvashatja ezt az üzenetet:<br /><br /><b>1. Ön nem regisztrált tagja az oldalnak</b><br />Ebben a GEDCOM-állományban az élő személyekre vonatkozó adatokat bizalmasan kezeljük. A nem regisztrált látogatók, illetve akik nem jelentkeztek be csak az elhunytak személyes adatait tekinthetik meg. A regisztrációhoz először kattintson a Belépés, majd az Új jelszó kérése hivatkozásra.<br /><br /><b>2. Ön rendelkezik felhasználónévvel és jelszóval...</b><br />Ez esetben Ön nem jelentkezett be vagy inaktív volt egy ideig és lejárt a munkamenete.<br /><br /><b>3. Az érintett adat jellege \"Diszkrét\"</b><br />A személy, akinek Ön a nevére kattintott azt kérte az adminisztrátortól, hogy adatait diszkrét módon kezeljék.<br />Ezekben az esetekben a személyes adatokhoz csak az adminisztrátorok férhetnek hozzá.<br /><br /><b>4. Ön kívül esik a \"Rokonsági útvonalon\"</b><br />Bizonyos esetekben előfordulhat - még akkor is, ha ön rendes tag <b>és</b> be is jelentkezett -, hogy ezt az üzenetet kapja: ekkor az érintett személy túl távoli rokona Önnek. Ezt az oldal adminisztrátora határozza meg az adott GEDCOM-ra vonatkozóan (Rokonsági fok maximáliás nagysága). <br />Példák:<br />Ha a Rokonsági fok maximális nagysága <b>1</b>, Ön csak a közvetlen családjának - apa, anya, testvérek - adatait láthatja (de a házastársakat, a testvérek gyermekeit már nem) <br /><br />Ha a Rokonsági fok maximális nagysága <b>2</b>, akkor Ön már láthatja a testvérei házastársának és az ő gyermekeinek adatait (de a gyermekek házastársait már nem).<br />Minél magasabb a Rokonsági fok maximális nagysága, annál távolabbi rokonokat láthat Ön<br /><br />Ha Ön úgy gondolja, hogy bizonyos adatokhoz hozzáférhet, a lapok oldalán lévő hivatkozáson át lépjen kapcsolatba az adminisztrátorral.";
$pgv_lang["more_help"]				= "<br />Ha szeretné, hogy a környezetérzékeny segítség elérhető legyen, győződjön meg arról, hogy a <b>Környezetérzékeny segítség megjelenítése</b> (a Segítség menüben) be van kapcsolva, és kattintson az érintett elem mögötti <b>?</b>-re.";
$pgv_lang["more_config_help"]			= "<br /><b>Bővebb információ</b><br />Több segítség, az elem melletti <b>?</b> -re kattintva érhető el.";
$pgv_lang["header_general_help"]		= "<div class=\"name_head\"><center><b>ÁLTALÁNOS INFORMÁCIÓ</b></center></div>";
$pgv_lang["best_display_help"]			= "A PhpGedView használatának optimális képernyő-felbontása 1024x768.<br />Ahhoz, hogy minden elem teljesen látható legyen, Önnek legalább ekkora felbontást kell beállítania.<br />Amennyiben alacsonyabb felbontást alkalmaz (pl. 800x600), vízszintesen kell majd görgetnie a képernyőt.";
$pgv_lang["preview_help"]			= "A Nyomtatható változat hivatkozásra kattintva minden olyan elem eltüntethető a képernyőről, melyek kinyomtatva nem mutatnak jól (menüpontok, \"beviteli mezők\", \"fölösleges\" hivatkozások, kérdőjelek a környezetérzékeny segítséghez stb).<br /><br />Az így létrejövő oldalon a lap alján megtalálhatja a Nyomtatás hivatkozást, melyre rákattintva elérheti nyomtatója párbeszédpaneljét. Nyomtatás után kattintson a <b>Vissza</b> hivatkozásra, és visszakerül a kiinduló oldalra.<br /><br />Megjegyzés: Bár a \"Nyomtatható változatból\" sok hivatkozás eltávolításra kerül, a megmaradók továbbra is kattinthatók.";
$pgv_lang["readme_help"]			= "<center>További információért olvassa el a <a href=\"readme.txt\" target=\"_blank\"><b>Readme.txt</b></a> állományt.</center>";

//-- Pages Help-messages
//-- Index-page
$pgv_lang["index_help"]				= "Ez a lap a Nyitóoldal, mely fogadja Önt a kiválasztott <a href=\"#def_gedcom\">GEDCOM</a> állományban. Ön bármikor visszatérhet ide a felső menüsorban található Nyitóoldal ikon segítségével. Ha az oldal több GEDCOM-állománnyal dolgozik, Ön egy lenyíló menüből választhatja ki a látni kívánt GEDCOM-ot.<br /><br />Ez a segéd oldal tartalma:<ul><li><a href=\"#index_portal\"><b>Nyitóoldal</b></a><li><a href=\"#header\"><b>Fejléc</b></a><li><a href=\"#menu\"><b>Menük</b></a><li><a href=\"#header_general\"><b>Általános információk</b></a><li><a href=\"#def\"><b>Definicciók</b></a></ul>";

//-- Index-page Header
$pgv_lang["header_help"]			= "<div class=\"name_head\"><center><b>FEJLÉC</b></center></div><br />A Fejléc megjelenik minden oldal tetején:<br />számos, az oldalon való navigációt segítő hivatkozást tartalmaz.<br />Mivel az oldal megjelenése a kiválasztott Asztaltéma#pgv_lang[redast]# függvényében eltérő lehet, ezek a fejlécet is érinthetik, így a hivatkozások is eltérőek lehetnek.<br />Az itt található hivatkozások a következők:";
$pgv_lang["header_search_help"]			= "Amilyen kicsi a kereső-mező, olyan hatékony.<br />Ön majdnem bármilyen keresést elvégezhet a segítségével a PhpGedView-oldon. Amint Ön a ' <b>&gt;</b>'-ra vagy a <b>Keresés</b> gombra kattint, átirányítjuk a keresés főoldalára, ahol megtekintheti a találati listát.<br />A keresésről annak főoldalán kaphat átfogóbb segítséget.";
$pgv_lang["header_lang_select_help"]		= "A PhpGedView egyik legfontosabb szolgáltatása a többnyelvűség támogatása, illetve a nyelvek közötti automatikus - a böngésző-beállítástól függő - választás.<br />Ha ez a választás nem történik meg automatikusan (melyet valószínűleg az \"Előnyben részesített nyelv\" helytelen böngésző-beállítása okozhatja), Ön módosíthatja az oldal nyelvét a <b>Nyelvválasztás</b> segítségével.<br />A Nyelvválasztás két módon jeleníthető meg:<br />1. Klasszikus  \"lenyíló\" listában.<br />2. A nemzeti zászlók segítségével.";
$pgv_lang["header_user_links_help"]		= "A hivatkozások kis csoportja, melyet a felhasználó minden oldalon ugyanott találhat (amíg meg nem változtatja az Asztaltémát).<br />Ha Ön még nem jelentkezett be, kizárólag a  <b>Belépés</b> hivatkozást láthatja.<br />Miután belépett, a következőket találja it:  <b>Bejelentkezve, mint (az Ön neve)</b>. Erre kattintva az Ön felhasználói adataihoz juthat.<br />A <b>Kilépés</b> hivatkozással jelentkezhet ki.<br />Ha Önnek vannak adminisztrátori jogosultságai, akkor szintén itt találja az <b>Adminisztráció</b> hivatkozását. Erre kattintva közvetlenül az Adminisztráció nyitólapjára juthat.";
$pgv_lang["header_favorites_help"]		= "A Kedvenceim lenyíló-listája az Ön által a személyes oldalon kiválasztott Kedvenceket tünteti föl. Szintén itt láthatók az oldal adminisztrátora által az aktív GEDCOM-állományból kiválasztott személyeket.<br />Az egyik Kedvencre kattintva közvetlenül elérhető az adott Személyes adatlap.<br />Kedvencek hozzáadásáról további segítséget kaphat az Ön személyes oldalán.";

//-- Index-page Menu
$pgv_lang["menu_help"]				= "<div class=\"name_head\"><center><b>MENÜPONTOK</b></center></div><br />Az oldalak fejlécében (lenyíló) menüpontokat találhat.<br /><br />A kurzor ikon fölé mozgatásával így elérheti az almenüket. A menüpontok ikonjára kattintva az almenüpontok közül az első helyen álló oldalra juthat.<br /><br />Ön a következő fő menüpontok közül választhat:<ul><li><a href=\"#menu_fam\">Nyitó oldal</a><br /><li><a href=\"#menu_myged\">MyGedView Portál</a><br /><li><a href=\"#menu_charts\">Grafikonok</a><br /><li><a href=\"#menu_lists\">Listák</a><br /><li><a href=\"#menu_annical\">Évfordulók</a><br /><li><a href=\"#menu_clip\">Családfa Metszési Kosara</a><br /><li><a href=\"#menu_search\">Keresés</a><br /><li><a href=\"#menu_help\">Segítség</a></ul>";
$pgv_lang["menu_famtree_help"]			= "Ön az oldalon elérhető összes GEDCOM-állomány közül választhat ezen a helyen. Minden GEDCOM-állománynak van egy ehhez hasonló egyéni Nyitóoldala. Ha az oldalon csak egy GEDCOM-állomány található, természetesen almenük nem érhetők el a Nyitóoldal ikonján keresztül.";
$pgv_lang["menu_myged_help"]			= "Ha Ön bejelentkezett, ezen menüpontban a következő elemeket találja meg: <ol><li>MyGedView Portál<br />Elvezeti Önt az Ön \"kezdőlapjára\".</li><br /><li>Felhasználói adataim<br />Itt szerkesztheti az Ön személyes felhasználói beállításait.</li><br /><li>Családfám<br />Ha Ön kiválasztotta a kezdő személyt ehhez a GEDCOM-állományhoz, ez a hivatkozás ennek a személynek az ősfájához fogja irányítani.</li><br /><li>Saját Személyes Adataim<br />Átirányítja Önt az Ön Személyes adatok oldalára, ahol az Önre és családjára vontkozó genealógiai adatok találhatók.</li></ol>";
$pgv_lang["menu_charts_help"]			= "Az összes működő grafikon érhető el erről a menüpontról:<dl><dt>Ősfa</dt><dd>Az aktuális GEDCOM-állomány ősfája, melynek kezdő személye lehet Ön (ha bejelentkezett), illetve egy Ön által kiválasztott személy.</dd><dt>Leszármazottak</dt><dd>A leszármazottak fája többé-kevésbé megfelel egy fordított ősfának.<br />Az összehasonlítás összességében megállja a helyét, de amíg az ősfa egy adott személy őseit mutatja meg, addig a leszármazottak fája egy személy leszármazottait tünteti fel. </dd><dt>Kronológiai</dt><dd>Ezen az oldalon egy adott személy életének eseményeit mutatjuk be az idő múlásával. <br />Tanulságos lehet két vagy több személy életét egymás mellett látni.</dd><dt>Rokonsági fok</dt><dd>Itt egy személynek Önhöz vagy egy másik személyhez fűződő rokonsági kapcsolatát ismerheti meg.</dd></dl>";
$pgv_lang["menu_lists_help"]			= "Ezen menüponton keresztül a következő listák jeleníthetők meg: <dl><dt>Személyek litája</dt><dt>Családok listája</dt><dd>Eben a két listában az aktuális GEDCOM-állomány személyeinek listáját találhatja.<br />Az első a személyeket, a második a családokat tünteti fel.</dd><dt>Források listája</dt><dd>Itt a GEDCOM-állományban szereplő összes forrást tekintheti meg. </dd><dt>Helyszínek hierarchiája</dt><dd>Itt a helyszínek alapján kereshet meg személyeket. Egy két oszlopos listát kap, melyből a bal oldalon találja a személyekhez, a jobb oldalon pedig a családokhoz kötődő helyeket.</dd><dt>Multimédia lista</dt><dd>Ezt a menüpontot csak az adminisztrátor engedélyével láthatja. <br />Az összes multimédia-állomány listáját tartalmazza, melyek az aktuális GEDCOM-hoz tartoznak. </dd></dl>";
$pgv_lang["menu_annical_help"]			= "Az Évfordulók a kiválasztott dátumhoz tartozó eseményeket tünteti fel az adott napon, hónapban vagy évben.<ol><li><a href=\"?help=day_month_help\"><b>Adott napon</b></a></li><li><a href=\"?help=day_month_help\"><b>Adott hónapban</b></a></li><li><a href=\"?help=day_month_help\"><b>Adott évben</b></a><br />Ezek a menük tovább viszik önt a Évfordulók hogy feltüntessék az összes eseményt az adott napon, hónapban vagy évben.</li></ol>";
$pgv_lang["menu_clip_help"]			= "Ön csak abban az esetben látja ezt a menüpontot, ha az adott GEDCOM-állományra vonatkozóan engedélyezett az adminisztrátor.<br /><br />A Metszési kosár lehetővé teszi, hogy Ön \"darabokat\" vágjon le a családfából.";
$pgv_lang["menu_search_help"]			= "A fejlécben található keresőmező részletesebb változata.";
$pgv_lang["menu_help_help"]			= "#pgv_lang[help_help_items]#";

//-- Index-page Portal
$pgv_lang["index_portal_head_help"]		= "<div class=\"name_head\"><center><b>NYITÓOLDAL</b></center></div>";
$pgv_lang["index_welcome_help"]			= "Ez a blokk a következőket közli:<br />Az aktuális GEDCOM-állomány, a dátum és az idő (ha az adminisztrátor engedélyezte) és a <b>Számláló</b>.<br />A számláló kizárólag a Nyitóoldalon illetve a személyi lapokon tüntethető fel. <br />A számláló az adott oldalt érintő \"találatokat\" rögzíti, vagyis azt, hogy az oldalt hányszor látogatták meg.<br />Nem ellenőrzi a látogató URL-jét, tehzát ha valaki visszatér az oldara, azt új találatként értelmezi. ";
$pgv_lang["index_login_help"]			= "Bár Ön majdnem az összes oldalon be tud jelentkezni, leggyakrabban mégis a nyitóoldalon teszi ezt meg, mivel csak ezután kaphat jogosultságot bizonyos adatok megtekintéséhez.<br />A <b>felhasználónév</b> és a <b>jelszó</b> begépelésével valamint a Belépés gombra való kattintással tud bejelentkezni.<br /><br />~ÚJ JELSZÓ KÉRÉSE~<br />Amennyiben Ön elfelejtette a jelszavát, kattintson erre a hivatkozásra egy új jelszóért.<br />Ennek hatására átkerül az \"Elvesztettem a jelszavamat\" oldalra.";
$pgv_lang["index_events_help"]			= "Ez a blokk az érintett GEDCOM-ból származó, a következő hónapban aktuális eseményeket tünteti fel.";
$pgv_lang["index_onthisday_help"]		= "Ez a blokk hasonlóan működik, mint az  \"Elkövetkező események\" blokk, viszont csak a mai napot érintő eseményeket tünteti fel.";
$pgv_lang["index_favorites_help"]		= "A GEDCOM Kedvencek sokban hasonlít a MyGedView Portálon található \"Kedvenceim\" blokkra azzal a különbséggel, hogy ez esetben az adminisztrátornak van joga felvenni, törölni vagy megváltoztatni a kedvenceket.<br />A blokk szerepe, hogy a látogatók figyelmét felhívja a különleges érdeklődésre számot tartó személy(ek)re. <br />A \"GEDCOM kedvencek\" minden oldal fejlécében, egy lenyílóból érhetők el.<br />Az ott található hivatkozások az adott személy adatlapjára mutatnak.<br /><br />Helykímélés miatt a szövegdobozok minimális információt hordoznak, a cellák jobb oldalán található nagyító segítségével juthat több adathoz.<br />A személy nevére kattintva Ön eljuthat az illető személyi lapjához. <br />Szintén a jobb oldalon találhatja a menüt, melyen bővebb információt vagy grafikonokat tartalmazó oldalakra vezető hivatkozásokat találhat.";
$pgv_lang["index_stats_help"]			= "Ebben a blokkban az aktuális GEDCOM-állományra vonatkozó legfontosabb statisztikai adatokat találhatja. <br />Ha Ön több információra kíváncsi, a lap alján találhat lehetőséget a kapcsolat felvételére.<br /><br />~LEGYAKORIBB VEZETÉKNEVEK BLOKK~<br />A GEDCOM-állományban legtöbbet előforduló vezetéknevek láthatók ebben a blokkban. A feltüntetett nevek számát az adminisztrátor szabja meg. <br /><br />A nevek természetesen kattinthatóak, így bővebben tájékozódhat az adott személyről az Személyek listája útján.";
$pgv_lang["index_common_names_help"]		= "A GEDCOM-állományban legtöbbet előforduló vezetéknevek láthatók ebben a blokkban. A feltüntetett nevek számát az adminisztrátor szabja meg. <br /><br />A nevek természetesen kattinthatóak, így bővebben tájékozódhat az adott személyről az Személyek listája útján.";
$pgv_lang["index_media_help"]			= "Ebben a blokkban a PhpGedView minden az Ön látogatásakor egy véletlenszerűen kiválasztott média-elemet jelenít meg.<br />A képre vagy a címére kattintva megtekintheti a teljes méretű változatot. <br />A kép alatt ezen kívül talál még egy hivatkozást az ábrázolt személy adatlapjához.";
$pgv_lang["index_loggedin_help"]		= "Ezen a helyen Ön nyomon követheti a bejelentkezett felhasználók számát.";
$pgv_lang["index_gedcom_news_help"]		= "A Hírek blokkja leginkább egy hirdetőtáblára hasonlít.<br />Az oldal admnisztrátora fontos bejelentéseket vagy érdekes híreket tehet itt közzé.<br /><br />Ha Önnek van valamilyen közérdekű, érdekes híre, küldje el az adminisztrátornak, aki felrakja azt a hirdetőtáblára.";

//-- Index-Page Help
$pgv_lang["help_help"]				= "Természetesen az volna a kívánatos, ha olyan programot alkotnánk, mely egyáltalán nem igényel magyarázatot, olyan egyszerű lenne, mint egy könyv olvasása. <br />Annak ellenére, hogy a program meglehetősen bonyolult, a felhasználói felületen Ön ezt általában nem veszi észre, majdnem az összes funkciója minden további magyarázat nélkül használható. <br />Viszont számos olyan látogatónk és felhasználónk van, akik nem túlzottan jártasak a számítógép és az internet használatában, bizonyos helyeken Segítséget kínálunk Önnek.<br />A Segítség menüben a következő elemek találhatók:";
$pgv_lang["help_page_help"]			= "<dl><dt><b>Segítség ehhez az oldalhoz</b></dt><dd>Minden oldalhoz elérhető egy általános, \"oldalspecifikus segítség\".<br />Ha Ön az adott oldalon jár, erre a menüpontra kattintva megtekintheti az oldal tartalmát bemutató \"oldalspecifikus segítséget\".<br />Az oldalspecifikus segítség az esetek többségében elég rövid. <br />Ha Önnek további tájékoztatásra van szüksége az oldalon található egyik elemről, akkor a Segítség menü harmadik lehetőségét vegye igénybe: a \"Környezetérzékeny segítséget\".</dd></dl>";
$pgv_lang["help_content_help"]			= "<dl><dt><b>A Segítség tartalomjegyzéke</b></dt><dd>Erre a menüpontra kattintva  Ön megtekintheti egy felugró ablakban az összes fontosabb segítség-elemet. <br />Ez az index a jövőben mind több elemet fog tartalmazni, mivel a kevésbé fontos elemek is folyamatosan felvételre kerülnek.</dd></dl>";
$pgv_lang["help_faq_help"]			= "<dl><dt><b>GYIK Lista</b></dt><dd>#pgv_lang[text_faq_help]#</dd></dl>";
$pgv_lang["help_HS_help"]			= "<dl><dt><b>Keresési Segítség</b></dt><dd>#pgv_lang[hs_intro]#</dd></dl>";
$pgv_lang["help_qm_help"]			= "<dl><dt><b>Környezetérzékeny segítség elrejtése / megjelenítése</b></dt><dd>Talán ez a menüpont lehet a leginkább kényelmes Önnek. Erre kattintva ki- és bekapcsolhatja a \"Környezetérzékeny segítséget\".<br />De mit is takar a \"Környezetérzékeny segítség\"?<br />Ha bekapcsolja, egy kérdőjelet találhat az egyes hivatkozások, lenyíló listák és gombok jobb oldalán. Ezekre a <b>?</b>-kre kattintva az adott elemről szóló segítség jelenik meg a felugró ablakban.<br />Természetesen a \"Környezetérzékeny segítség elrejtése \" kiválasztásával a kérdőjelek eltűnnek addig, amíg újra erre a menüpontra nem kattint.</dd></dl>";

//-- Index-page Definitions
$pgv_lang["def_help"]				= "<div class=\"name_head\"><center><b>DEFINÍCIÓK</b></center></div><br />A Segítségek szövegében olvasható fontosabb kifejezések magyarázata:";
$pgv_lang["def_portal_help"]			= "Ezen az oldalon (sok másikhoz hasonlóan) a portál hasonlít egy étterem előcsarnokához. Ez az a hely, ahová Ön belép, de sok fontos lehetőséget is itt találhat meg, mint pl. a menük és magyarázatok.";
$pgv_lang["def_gedcom_help"]			= "A GEDCOM-állomány tartalmazza a családra vonatkozó összes információt. <br />Minden tény, dátum, esemény ebben az állományban található meg.<br />A GEDCOM-állományok igen szigorú szabályok alapján épülnek fel, mivel számos programnak platform- és rendszerfüggetlenül kell tudnia használni őket.";
$pgv_lang["def_gedcom_date_help"]		= "Mivel a GEDCOM-állományokban az elemek megjelenítésének nemzetközi szabályokat kell követnie, a dátumok jelölése is megállapodás szerint történik.<br /><br />Habár a GEDCOM-állományban a dátumok szabad mezőként szerepelnek (azaz Ön akár szövegként is megadhatja őket), a következő magyarázatok segítik Önt a helyes dátumbevitelben:<br />A teljes dátumformátum NN HHH ÉÉÉÉ, pl.<br />01 Mar 1801 vagy 14 Dec 1950<br />Ha a szóban forgó dátum egy része hiányzik, az a bevitelnél kihagyható, pl. <br />Mar 1801 vagy 14 Dec<br />Ha Ön nem biztos valamiben, vagy a dátum nem nyert megerősítést, a következő beviteli módok használhatók:<br />abt Mar 1801 (abt = about = körül)<br />bef 20 Dec 1950 (bef = before = előtt)<br />aft 1949 (aft = after = után)<br />Ügyeljen arra, hogy a dátumokat és a rövidítéseket angolul rögzítse, hiszen ez a program fogja a dátumokat és rövidítéseket a kívánt nyelvre fordítani.<br />Emellett a program számításokat is végez a dátumokkal, tehát ha ilyen módon pontatlan dátumok kerültek rögzítésre, a számítások is hibásak lesznek.";
$pgv_lang["def_pgv_help"]			= "A PhpGedView (vagy PGV) nem csupán statikus lapokat jelenít meg, hanem dinamikusan változik és sokoldalúan testre szabható.<br /><br />A PhpGedView John Finlay által alkotott, a GEDCOM-állományok online megjelenítését szolgáló program. John egyedül látott hozzá a program fejlesztéséhez, azonban azóta fejlesztőkből és fordítókból álló nemzetközi csapat gyűlt köré, akik a program tökéletesítésén dolgoznak. A GEDCOM-állományok megjelenítésén kívül a PhpGedView lehetővé teszi a az online bővítést és szerkesztést is.";
$pgv_lang["def_theme_help"]			= "Az oldal számos eltérő \"kinézettel\", más néven Asztaltémával rendelkezik.<br />Az oldal adminisztrátora mindig kijelöl egy Asztaltémát kezdőként, tehát mindenki, aki meglátogatja az oldalt, ugyanolyannak fogja látni. Ha az adminisztrátor lehetővé teszi, hogy a bejelentkezett felhasználók kiválaszthassák saját Asztaltémájukat, akkor ők lecserélhetik arra, ami nekik a legjobban tetszik.<br />Ha egy felhasználó eltérő Asztaltémát választ, a beállítás akkor lép életbe, mikor bejelentkezik az oldalra.";

//-- Index-page MyGEDCOM
$pgv_lang["mygedview_portal_help"]		= "Ez az Ön Személyes MyGedView oldala.<br />Itt olyan hivatkozásokat talál - mint a <b>Személyes adataim,</b> az <b>Én és a családom</b> oldal (ez az Ön személyi lapja) és a <b>Családfám</b> -, melyek megkönnyítik az Ön személyes adataihoz való hozzáférést.  .<br />Ezeken kívül többek között olyan blokkokat is használhat itt, mint az<b>Üzeneteim</b>, és a <b>Hírlap</b> (egyfajta jegyzetfüzet).<br /><br />Az oldal felépítése hasonló a Nyitóoldaléhoz, de míg annak a tartalmát az oldal adminisztrátora állítja össze, addig ennek a szerkesztését Ön végezheti el.<br /><br />Az oldal felhasználó üdvözlő blokkjában találhatja azt a hivatkozást, mely az oldal testre szabásában segíti Önt.<br />A következő blokkok állnak az Ön rendelkezésére: ";
$pgv_lang["mygedview_customize_help"]		= "Mikor Ön első alkalommal belép ide, akkor már találhat néhány blokkot az oldalon.<br />Ha szeretné, természetesen van lehetőség a portál módosítására.<br />A hivatkozásra kattintva egy űrlap jelenik meg a felugró ablakban, melyben Ön blokkokat adhat hozzá, törölhet, vagy megváltoztathatja a sorrendjüket.<br />További magyarázat az űrlapon érhető el.";
$pgv_lang["mygedview_message_help"]		= "Ebben a blokkban az Önnek íródott üzeneteket találhatja meg.<br />Természetesen Ön is küldhet üzenetet mind a felhasználóknak, mind az adminisztrátornak.<br />A PhpGedView levelező rendszere úgy lett kialakítva, hogy védje az Ön bizalmas jellegű adatait. Önnek nem kell itt meghagynia e-mai címét, és mások sem láthatják azt.";
$pgv_lang["mygedview_favorites_help"]		= "A Kedvenceim a könyvjelzőhöz hasonlóan működik:<br />Tételezzük fel, hogy van egy személy a családfán, akinek az adataira Ön rendszeresen kíváncsi.<br />Csupán annyit kell tennie, hogy elmegy az adott személyi lapra és kiválasztja a \"Hozzáadás a Kedvencekhez\" opciót a Kedvencek lenyíló-listájából. Ezzel Ön a személyt kijelölte és hozzáadta a Kedvencekhez. <br />Bárhol is járjon az oldalon, elegendő, ha rákattint az illető személy nevére a Fejlécben található \"Kedvenceim\" lenyíló-listában, és ez átirányítja Önt az érintett személyi lapjára.<br /><br />Helykímélés miatt a szövegdobozok minimális információt hordoznak, a cellák jobb oldalán található nagyító segítségével juthat több adathoz.<br />A személy nevére kattintva Ön eljuthat az illető személyi lapjához. <br />Szintén a jobb oldalon találhatja a menüt, melyen bővebb információt vagy grafikonokat tartalmazó oldalakra vezető hivatkozásokat találhat.";
$pgv_lang["mygedview_myjournal_help"]		= "Ön ebbe a blokkba írhat saját használatra jegyzeteket (vagy emlékeztetőket).<br />Természetesen ha Ön beír ide egy jegyzetet, azt a következő látogatáskor is itt fogja találni.<br /><br />Ezek a feljegyzések nem férhetők hozzá a többi felhasználó számára.";
$pgv_lang["mygedview_welcome_help"]		= "<dl>~FELHASZNÁLÓ ÜDVÖZLŐ BLOKK ~<dt>A Felhasználó Üdvözlő Blokk a következőket tünteti fel:</dt><dd>- Az aktuális GEDCOM-állomány</dd><dd>- A dátum és az idő</dd><dd>- Hivatkozások a következőkhöz::</dd><dd> - - Felhasználói adataim</dd><dd>- - Családfám (lásd még a megjegyzést)</dd><dd>- - Saját Személyes Adataim (lásd még a megjegyzést)</dd><dd>- - Állítsa be az Ön személyes oldalát</dd></dl><b>Megjegyzés:</b><br />Az \"Én és a családom\" valamint a \"Családfám\" hivatkozásokat csak akkor láthatja, ha Ön is szerepel az aktuális GEDCOM-állományban.<br />Tehát ez alapján lehetséges, hogy Ön szerepel az egyik GEDCOM-állományban és így megjelenik a fenti két hivatkozás, míg egy másik állomány esetében, melyben Ön nem szerepel, nem jelennek meg.";

//-- Pedigree-page
$pgv_lang["help_pedigree.php"]			= "A felhasználók többsége tudja, hogy mit takar az Ősfa kifejezés, de egy rövid összefoglaló az ezen az oldalon látható Ősfáról hasznos lehet:<br />Az ősfa valójában a kezdő személy összes ősének felsorolása.<br />Mikor Ön meglátogatja az oldalt, a bal oldalon látható személy a kezdő személy (bejelentkezés után tetszőleges kezdő személy választható).<br /><br />Az \"összes ős\" tehát az apát és az anyát, az ő szüleiket, stb. jelenti.<br />Ezen az oldalon az ősfa grafikus formában jelenik meg, tehát Önnek nem kell azzal töltenie az idejét, hogy sok oldalnyi szövegen rágja keresztül magát, hogy megtalálja a keresett őseit.<br />Az egyes személyek szövegdobozokban jelennek meg a képernyőn. <br /><br />* SZÖVEGDOBOZOK AZ ŐSFÁN<br />Ha az ősfán a részletek megmutatása be van kapcsolva, Ön láthatja a személyek nevét, valamint a születési és elhalálozási dátumát.<br />Ha egy személy nevére rákattint, egyenesen az illető személyi lapjára kerül<br />Ha a \"részletek mutatása\" be van kapcsolva, két ikon jelenik meg a szövegdobozban:<br /><br />* ŐSFA-IKON a SZÖVEGDOBOZBAN<br />Ha a \"részletek mutatása\" be van kapcsolva, egy ősfa-ikon lesz látható a szövegdobozban, melyet az oldal beállításaitól függően az kattintással vagy az egér áthúzásával aktiválhat.<br />Aktiválás után egy kis almenü jelenik meg:<br />Az \"Ősfa\" és a \"Leszármazottak\" hasonlóak a főmenüben található elemekhez, viszont az így megjelenő grafikonok  kezdő személye abban szövegdobozban lévő személy, ahonnan elindítottuk az akciót.<br />Ezen kívül itt szerepel még a  \"Családtagok házastárssal\" opció, mely alatt látható a házastárs neve, azt követően pedig a gyermekek neve.<br />Az összes név kattintható.<br /><br />* NAGYÍTÓ-IKON A SZÖVEGDOBOZBAN<br />Ez az ikon felnagyítja a szövegdobozt, így több részlet válik láthatóvá, további dátumokat és eseményeket találhat így meg (a nevek kattinthatóak).<br /><br />* A NYILAK<br />A jobb vagy bal szélső szövegdobozok mellett jobbra vagy balra mutató nyilakat találhat. <br />A nyilakra kattintva  \"görgethető\" a képernyő a nyílnak megfelelő irányba.<br /><br />További segítség az oldalon érhető el, a mezők és hivatkozások mögött látható <b>?</b>-re kattintva.";
$pgv_lang["show_full_help"]			= "Ennek a gombnak a segítségével Ön minden részletet megmutathat az egyes szövegdobozokban vagy el is rejtheti azokat.<br />A részletek elrejtésével egy képernyőn több szövegdoboz jeleníthető meg.<br /><br />Az elrejtett részletek esetében is lehetőség van az adatok feltárására, ha a Nagyító rendelkezésre áll a normál nézetben, ami attól függ, mit állított be az oldal adminisztrátora.<br />Ha Önnek kattintania kell a Nagyítóra részletekért, akkor ebben az esetben is kattintson a szövegdobozra.<br />Ha Önnek elegendő a Nagyítóra vinni a kurzort a részletekért, akkor ebben az esetben is húzza a kurzort az \"egyszerűsített\" szövegdobozra.";
$pgv_lang["talloffset_help"]			= "Ezzel az opcióval a szövegdobozok elrendezése állítható a képernyőn (\"álló\" és \"fekvő\") <br /> Ennek a beállításnak a módosítása hasznos lehet, ha Ön ki szeretné nyomtatni az oldat vagy másfajta képernyővel rendelkezik.";
$pgv_lang["rootid_help"]			= "Ha Ön a családfát egy másik kezdő személlyel kívánja megjeleníteni, akkor ebbe a bevíteli mezőbe írja be a személy azonosítóját.<br />Ha nem ismeri a személy azonosítóját, használja az <b>Azonosító</b> hivatkozást.<br /><br /><b>Azonosító szám</b><br />A PhpGedView-ban használt azonosító szám nem egyezik meg a személy egyetlen hivatalos azonosító számával sem!<br />Ezt a számot a GEDCOM-állományt létrehozó program rendeli hozzá a személyhez.";
$pgv_lang["PEDIGREE_GENERATIONS_help"]		= "Itt állíthatja be az egy oldalon megjelenítendő generációk száma.<br /><br />A helyes szám a képernyő méretének és megjelenített adatok részletezettségének függvényében változik.";

//-- LOGIN-page
$pgv_lang["login_page_help"]			= "Ezen az oldalon van lehetőség a belépésre, új jelszó kérésére, valamint új felhasználó regisztrációjára.";
$pgv_lang["username_help"]			= "Ebben a beviteli mezőbe gépelje be felhasználónevét.<br /><br /><b>Ügyeljen arra, hogy a mező érzékeny a kis- és nagybetűkre.</b> Ez azt jelenti, hogy a <b>ANevem</b> <u>nem</u> ugyan az mint a <b>anevem</b> vagy a <b>ANEVEM</b>.";
$pgv_lang["password_help"]			= "Ebben a beviteli mezőbe gépelje be jelszavát.<br /><br /><b>Ügyeljen arra, hogy a mező érzékeny a kis- és nagybetűkre.</b> Ez azt jelenti hogy a <b>JELszó</b> <u>nem</u> ugyan az mint a <b>jelszó</b> vagy a <b>JELSZÒ</b>.";
$pgv_lang["login_buttons_help"]			= "Két gombot találhat itt, melyek a rendszerbe való belépést szolgálják.<br />Az, hogy a felhasználónév és a jelszó megadása után melyik oldalra kerül, attól függ, melyik gombra kattintott.<br /><br />* A <b> Belépés </b> gomb<br />Ha erre kattint, Ön arra az oldalra fog kerülni, ahonnan ide érkezett.<br />Tehát ha Ön úgy kattint a \" Belépés \" gombra, hogy előtte az Ősfa oldalán járt, akkor oda is fog visszatérni.<br /><br />* Az <b> Adminisztráció </b> gomb<br />Ha Önnek adminisztrátori jogosultsága van, akkor kattinthat erre a gombra, hogy egyenesen az Adminisztráció oldalára kerüljön.";
$pgv_lang["login_buttons_aut_help"]		= "BEJELENTKEZŐ GOMBOK<br /><br />Két gombot találhat itt, melyek a rendszerve való belépést szolgálják.<br />Az, hogy a felhasználónév és a jelszó megadása után melyik oldalra kerül, attól függ, melyik gombra kattintott.<br /><br />* A <b> Belépés </b> gomb<br />Ha erre a gombra kattint, akkora bejelentkezés után a MyGedView Portálra kerül, ahol szerkesztheti a beállításait, úk kedvenceket vehet föl vagy a régieket szerkesztheti, üzeneteket küldhet és fogadhat stb.<br /><br />* Az <b> Adminisztráció </b> gomb<br />Ha Önnek adminisztrátori jogosultsága van, akkor kattinthat erre a gombra, hogy egyenesen az Adminisztráció oldalára kerüljön.";
$pgv_lang["new_password_help"]			= "Amennyiben Ön elfelejtette a jelszavát, kattintson erre a hivatkozásra egy új jelszóért.<br />Ennek hatására átkerül az \"Elvesztettem a jelszavamat\" oldalra.";
$pgv_lang["new_user_help"]			= "Ha Ön olyan látogatója a honlapnak, aki szeretné regisztráltatni magát, kattintson ide.<br />Ennek hatására átkerül \"Regisztráció kérése\" oldalra.";
$pgv_lang["mygedview_login_help"]		= "Ha Ön el szeretné érni a MyGedView Portált, regisztráltatnia kell magát a rendszerben.<br /><br />A MyGedView Portál segítségével nyilvántarthatja \"kedvenceit\", hírlapot vezethet, kezelheti az üzeneteit, láthatja a bejelentkezett felhasználókat és tetszése szerint átalakíthatja a PhpGedView-t.<br /><br />Kérjük, a belépéshez adja meg a felhasználónevét és jelszavát.";

//-- Descendancy-page
$pgv_lang["help_descendancy.php"]		= "Ez az oldal egy adott személy leszármazottait tünteti fel.<br /><br />Önnek kiválaszthatja a kezdő személyt ezen az oldalon, vagy eljuthat ide, ha egy másik oldalon a <b>Leszármazottak</b> hivatkozásra kattint.";
$pgv_lang["desc_rootid_help"]			= "Ha Ön a családfát egy másik kezdő személlyel kívánja megjeleníteni, akkor ebbe a bevíteli mezőbe írja be a személy azonosítóját.<br />Ha nem ismeri a személy azonosítóját, használja az <b>Azonosító</b> hivatkozást.<br /><br /><b>Azonosító szám</b><br />A PhpGedView-ban használt azonosító szám nem egyezik meg a személy egyetlen hivatalos azonosító számával sem!<br />Ezt a számot a GEDCOM-állományt létrehozó program rendeli hozzá a személyhez.";
$pgv_lang["desc_generations_help"]		= "Itt állíthatja be az egy oldalon megjelenítendő generációk száma.<br /><br />A helyes szám a képernyő méretének és megjelenített adatok részletezettségének függvényében változik.";
//-- show_full is used from pedigree

//-- Time line-page
$pgv_lang["help_timeline.php"]			= "Ezen az oldalon egy vagy több személy életének eseményei tekinthetők át az idő múlásával.<br />Ennek megfelelően Ön megvizsgálhatja pl. két vagy több személy sorsát egy adott időpontban.<br /><br />Ha egy másik oldalon kattint a \"Kronológia\" ivatkozásra, akkor azt az egy személyt nézheti meg ezen a grafikonon.<br />Ha a fejléc menüpontján keresztül jutott el ide, a kezdéshez meg kell adni a személy azonosítóját a megfelelő beviteli mezőben.";
$pgv_lang["add_person_help"]			= "Ön ebben a Kronológiában több személyt is feltüntethet.<br />A személy azonosítóját ebben a beviteli mezőben kell feltüntetni.<br />Amennyiben nem tudja az azonosítót, használja az \"Azonosító\" hivatkozást.";
$pgv_lang["remove_person_help"]			= "Kattintson erre a hivatkozásra, ha el kívánja távolítani az adott személyt a Kronológiából.";
$pgv_lang["show_age_marker_help"]		= "Ha bejelöli ezt a mezőt, megjelenik az életkor jelző, melyet Ön a Kronológiában előre-hátra mozgathat. <br />Az életkor jelző megfelelő eszköz arra, hogy Ön ellenőrizhesse a személy életkorát egy adott esemény idején.<br />Az életkor jelző minden egyes személy esetében be- és kikapcsolható.";

//-- Relationship-page
$pgv_lang["help_relationship.php"]		= "Ezen az oldalon Ön megjelenítheti két személy rokonsági viszonyait. <br />Az eljárás nem igényli, hogy a két személy közvetlen vérrokonságban álljon egymással, mivel a program bármilyen rokoni kapcsolatot képes megtalálni.";
$pgv_lang["relationship_id_help"]		= "Ha Ön valamelyik másik oldalon szereplő hivatkozáson át került ide (pl. a \"Rokonsága velem\" segítségével), akkor az adott két személy közötti rokoni kapcsolatot fogja itt megtalálni.<br />Egyéb esetekben Önnek meg kell adni a személyek azonosítóját.<br />Amennyiben nem tudja az azonosítókat, használja az \"Azonosító\" hivatkozást.";
$pgv_lang["next_path_help"]			= "Erre a gombra kattintva megtudhatja, van-e még egy másik, \"alternatív\" rokoni kapcsolat a két személy között. Az előző útvonalat újra megtekintheti, ha a sorszámával ellátott hivatkozásra kattint.";
$pgv_lang["follow_spouse_help"]			= "Ha Ön ezt a jelölőnégyzetet <b>nem</b> jelöli meg, akkor csak a vérrokonság kerül feltüntetésre.<br />Ha a négyzetet bejelöli, akkor a házastárson keresztüli rokoni kapcsolatokat is megtekintheti.";

//-- Indilist-page
$pgv_lang["help_indilist.php"]			= "Ezen az oldalon Ön megtekintheti a személyek listáját.<br /><br />A listában a vezetéknév szerepel elsőként, ábécé-rendbe szedve.<br />A lista megjelenítése a következőktől függ:<br /><b>1.</b> A kezdőbetű, melyre Ön kattintott.<br /><b>2.</b> Megjeleníthető csak a vezetéknevek illetve a teljes nevek listája.<br /><br />Ha erről a témakörről további tájékoztatást igényel, kattintson az egyes elemek mögött látható ?-re.";
$pgv_lang["alpha_help"]					= "Az ábécé-index egyes betűire kattintva az adott betűvel kezdődő nevek jeleníthetők meg.<br />Az utolsó előtti elem lehet a listában az <b>\"pgv_lang[unknown]\"</b><br />Ez akkor jelenik meg, ha a GEDCOM-állományban olyan személyek vannak, akiknek nincs rögzítve a vezetékneve (pl. a szerkesztő nem ismerte), vagy a támogatott nyelven nem értelmezhető karakterekből áll.<br /><br /><b>Figyelem!</b><br />Ha a GEDCOM-állományban az ismeretlen személy neve eredetileg valamilyen kóddal lett rögzítve (pl. n.a., ismeretlen), akkor az <b>\"pgv_lang[unknown]\"</b> hivatkozásra kattintva <b>nem</b> fog szerepelni a találati listában. Ön úgy találhatja meg ezeket a személyeket, ha a kód kezdőbetűjére (pl.\"<b>N</b>\" vagy \"<b>I</b>\") kattint.<br />Ez abból fakad, hogy a program csak azt ellenőrzi, hogy a GEDCOM-állományban a vezetéknév pozíciója ki van-e töltve.<br /><br />Az ábécé-index végén szerepel a <b>\"pgv_lang[all]</b>\" hivatkozás. Erre kattintva megjelenik a GEDCOM-állományban szereplő összes vezetéknév.<br /><br /><b>Miért hiányoznak egyes betűk?</b><br />Előfordulhat, hogy az ábécé-index egyes betűi \"hiányoznak\". <br />Természetesen nem vesztek el, csupán arról van szó, hogy ilyen kezdőbetűjű vezetéknevek nem szerepelnek az adott GEDCOM-állományban.";
$pgv_lang["name_list_help"]			= "Ez a táblázat egyaránt tartalmazhatja a keresztnevek vagy a teljes nevek listáját.<br />Mindkét esetben a megjelenített keresztnevek azzal a betűvel kezdődnek, melyet Ön kiválasztott az ábécé-indexből, kivéve, ha Ön a <b>Mind</b> hivatkozásra kattintott.<br /><br />Az, hogy a keresztnevek vagy a teljes nevek listáját látja, a táblázat alatt látható hivatkozás állapotától függ.";
$pgv_lang["skip_sublist_help"]			= "Alapbeállításként Ön a neveknek egy közbülső - csak a vezetékneveket tartalmazó - listáját látja, miután kiválasztott egy betűt az ábécé-indexből.<br />Ha Ön erre a hivatkozásra kattint, ezt a közbülső listát átugorhatja, és közvetlenül a teljes nevek listájához kerülhet.";

//-- Families-page
$pgv_lang["help_famlist.php"]			= "Ezen az oldalon Ön megtekintheti a családok listáját.<br /><br />A listában a vezetéknév szerepel először, ábécé-rendbe szedve.<br />A lista megjelenítése a következőktől függ:<br /><b>1.</b> A kezdőbetű, melyre Ön kattintott.<br /><b>2.</b> Megjeleníthető csak a vezetéknevek illetve a teljes nevek listája.<br /><br />Ha erről a témakörről további tájékoztatást igényel, kattintson az egyes elemek mögött látható ?-re.";
$pgv_lang["help_family.php"]			= "Ezen az oldalról Ön áttekintést kaphat az előző oldalon kiválasztott családról.<br />Fentről lefelé haladva a következő elemeket találja itt:<br />A férj és a szülei.<br />A feleség és a szülei.<br />A gyermekeik.<br /><br />A szövegdobozok tartalma és kinézete megegyezik az Ősfa és a Leszármazottak fája esetében alkalmazottal.<br />A szülők szövegdobozának jobb oldalán látható egy nyíl, amennyiben az illetőnek további ősei is léteznek ebben az állományban. A nyílra kattintva az adott család családi információs lapjára juthat.<br />A gyermek(ek) szövegdoboza(i) alatt találhatja a \"Gyermek hozzáadása a családhoz\" hivatkozást.<br />A gyermekek szövegdoboza mellett látható a \"Információk erről a családról\" című táblázat.<br />Ha Önnek megfelelő jogosultsága van, szerkesztheti, törölheti, bővítheti az itt található adatokat.<br /><br />A képernyő jobb oldalán a következő ikonokat és hivatkozásokat találhatja: \"A házaspár mutatása a Kronológiában\", \"A GEDCOM-rekord megtekintése\", illetve (ha engedélyezett) \"Hozzáadás a családfa-ágak kosarához\".<br /><br /><br />Ha szeretné, hogy a környezetérzékeny segítség elérhető legyen, győződjön meg arról, hogy a <b>Környezetérzékeny segítség megjelenítése</b> (a Segítség menüben) be van kapcsolva, és kattintson az érintett elem mögötti <b>?</b>-re.";
$pgv_lang["add_child_help"]			= "Erre a hivatkozásra kattintva Önnek lehetősége van további gyermekek hozzáadására.<br /><br />A gyermek hozzáadása igen egyszerű: Kattintson a hivatkozásra, majd töltse ki a megjelenő űrlapot.";
//-- same variables as individuals page

//-- Source list-page
$pgv_lang["help_sourcelist.php"]		= "Ezen az oldalon Ön megtekintheti a források listáját.<br />A személyek és a családok listájával ellentétben itt nincsen ábécé-index a lap tetjén. Ez azért van, mert az egyes források kapcsolódhatnak kereszt- és vezetéknevekhez, lehetnek nyilvános adatbázisok, intézmények stb., ami igen megnehezítené egy átfogó rangsor kialakítását. A források neve ábécé-rendben látható úgy, ahogy a GEDCOM-állományban is tárolva vannak.<br /><br /><b>FORRÁSOK</b><br />Források nélkül nem építhetjük fel adatbázisunkat. Minden információ, melyet az adatbázisunkban tárolunk, egy forráson alapul. Forrás lehet egy rokon, egy intézmény, nyilvános adatbázis stb.<br />Egy forrás kapcsolódhat több személyhez, illetve egy személyhez is számos forrást lehet kötni. Ön  minden egyes eseményhez kapcsolódóan rendelkezhet több forrással is, függetlenül attól, hogy az születési dátum, foglalkozás, házasság, gyermek születése, stb.";
$pgv_lang["sourcelist_listbox_help"]		= "Ebben a táblázatban Ön a források nevét láthatja úgy, ahogyan azok a GEDCOM-állományban tárolva vannak.<br />A nevek ábécé-rendben szerepelnek.<br /><br />Mikor Ön az egyik forrásra kattint, átkerül a forrás információs lapjára, ahol megtudhatja, hogy mely személyekhez/családokhoz kapcsolódik az adott forrás.";

//-- Sources-page
$pgv_lang["help_source.php"]			= "Ezen a lapon Ön megtekintheti a kiválasztott forrásra vonatkozó részleteket, abban a formában, ahogy az a GEDCOM-állományban eltárolásra került. <br /><br />Ezen kívül egy listát is talál itt azokról a személyekről és családokról, akik kapcsolódnak ehhez a forráshoz.<br /><br />Ha az oldal adminisztrátora engedélyezte, további egy vagy két ikont is láthat itt:<br />A GEDCOM-rekord megtekintése,<br />Hozzáadás a családfa-ágak kosarához.<br /><br />További segítséget az oldalon látható <b>?</b>-re kattintva kaphat.";
$pgv_lang["sources_listbox_help"]		= "Ebben a táblázatban azoknak személyeknek és családoknak a neve található, melyek kapcsolódnak ehhez a forráshoz.<br />A neveket ábécé-rendbe szedve tüntetjük fel.<br /><br />Ha Ön az egyik névre kattint, akkor az érintett személy vagy család személyi lapjára jut.";
$pgv_lang["show_source_gedcom_help"]		= "Erre a hivatkozásra kattintva a GEDCOM-állományban tárolt információ jelenik meg eredeti formájában egy felugró ablakban.";
$pgv_lang["add_source_clip_help"]		= "Erre a hivatkozásra kattintva Ön hozzáadhatja az aktuális forrást a Metszési kosár -hoz hogy később lehozhassa és az ön genealógiai programjába importálhassa.";
$pgv_lang["delete_source_help"]			= "Erre az opcióra kattintva Ön törlésre jelöli ki az aktuális forrást.<br />Mit is jelent ez?<br />Tegyük fel, hogy Önnek alapos indoka van a forrás eltávolítására. A hivatkozásra való kattintás után megjelenik egy ablak, melyben megerősítheti törlési szándékát, vagy elvetheti azt.<br /><br />Ha Ön befejezi a folyamatot, egy kis idő múlva egy újabb felugró ablak tájékoztatja Önt, hogy a forrás törlésre került.<br /><br />Azonban ha folytatja látogatását az oldalon, láthatja, hogy a forrás ugyanúgy látható és használható, mint azelőtt volt.<br /><br />De ez <b>egyáltalán nem</b> hiba!<br />Az oldal adminisztrátora fog kapni egy üzenetet, miszerint változtatás történt a GEDCOM-állományban, és Ön eltávolított egy forrást.<br />Ezt az adminisztrátornak kell jóváhagyni (vagy elvetni), mely után a változtatást már nem lehet visszavonni.<br />Kérdéses esetben az adminisztrátor kapcsolatba fog Önnel lépni.";

//-- Persons per Place-page
$pgv_lang["help_placelist.php"]			= "(azaz személyek egy adott helyen)<br /><br />Ezen az oldalon Ön áttekintheti, hogy egy adott helyszínhez mely személyek és családok kötődnek.<br /><br />Ha van valamilyen kapcsolat egy személy/család és egy esemény között egy adott helyszínen, akkor a program meg fogja azt találni Önnek.<br /><br />Az eredmények egy két oszlopos táblázatban fognak megjelenni:<br />Egyikben a személyek, a másikban a családok szerepelnek.<br /><br /><br />Ha szeretné, hogy a környezetérzékeny segítség elérhető legyen, győződjön meg arról, hogy a <b>Környezetérzékeny segítség megjelenítése</b> (a Segítség menüben) be van kapcsolva, és kattintson az érintett elem mögötti <b>?</b>-re.";
$pgv_lang["ppp_default_form_help"]		= "<b>ALAPÉRTELMEZETT RANGSOR</b><br />A helyszíneket az alapértelmezett sorrendben mutatjuk meg Önnek.<br />Ez azt jelenti, hogy a GEDCOM-állományban semmiféle speciális rangsor nem található, vagyis az oldalon előzetesen beállított sorrendet alkalmazzuk.<br /><br />Ha ettől eltérő hierarchiát találunk a GEDCOM-állományban, akkor azt a sor végén látható (...)-ben mutatjuk meg Önnek.";
$pgv_lang["ppp_match_one_help"]			= "RANGSOR A GEDCOM-BÓL<br />A helyszíneket a GEDCOM-állományban található hierarchia szerint mutatjuk be. <br />Ez a beállítás fölülírja az alapértelmezett rangsort, melyet akkor használunk, ha a GEDCOM-állományban nem szerepel speciális hierarchia.";
$pgv_lang["ppp_numfound_help"]			= "A program által talált egyezések száma. <br />Ha Ön továbbra is lát egy táblázatot helyszínekkel, akkor még nem érte el a legalsó szintet.<br />Ott választhat nevet a felkínált <b>Névlistából</b> vagy módosíthatja keresését, ha egy másik helyszínt választ a névlista fölött található <b>Helyszínlistából</b>.";
$pgv_lang["ppp_levels_help"]			= "Ez a lista megmutatja az aktuálisan megjelenített helyszín-szinteket. <br />A helyszíneket bemutató táblázat tulajdonképpen a bal szélen látható helyszín-szint almenüjének felel meg.<br /><br />Például:<br />Az (alapértelmezett) sorrend a következő: város, megye, állam/tartomány, ország<br />Az aktuális szint a \"Felső szint\", így a táblázat a GEDCOM-állományban található országokat tartalmazza.<br />Ha az aktuális szint az \"USA, Felső szint\" , akkor a táblázat az USA államait mutatja meg.<br /><br />Ön természetesen kattinthat az egyes szintekre, hogy egy vagy több szinttel visszalépjen.";
$pgv_lang["ppp_placelist_help"]			= "Ebben a táblázatban a megtalált helyszíneket tüntetjük fel. A listában található nevek természetesen kattinthatók. Rájuk kattintva úgy működnek, mint egy szűrő: egy szinttel mélyebbre viszik Önt. Csupán a legfelső szinten nem jelenik meg névlista, mindegyik alsóbb szinten láthatja az oda tartozó személyeket és családokat.";
$pgv_lang["ppp_name_list_help"]			= "Ez a táblázat megmutatja az adott helyszínhez bármilyen módon kötődő személyeket és/vagy családokat.<br /><br />A listában található nevek természetesen kattinthatók.<br />Rájuk kattintva elvezetik Önt az adott személy vagy család információs lapjára.<br /><br />Ön természetesen megváltoztathatja ezt a listát, ha a feltüntetett helyszínek valamelyikére kattint.";

//-- Multimedia-page
$pgv_lang["help_medialist.php"]			= "A multimédia lista minden, a GEDCOM-állományban található multimédia-elemet feltüntet.<br /><br />Az egyes multimédia-elemek dobozában megtalálható az állomány neve, valamint a személy(ek) és család(ok) neve (mind kattintható), melyeket Ön az adott elemhez hozzárendelt. <br /><br />Egy személy vagy család nevére kattintva a személyi laphoz vagy a családi információs laphoz juthat el.<br /><br />A multimédia-elem nevére vagy magára a multimédia-elemre kattintva (az állomány kiterjesztésétől függően) a PhpGedView belső képnézőjében vagy az Ön böngészőjéhez társított képnézőben megtekintheti az állományt.<br /><br /><br />A jobb egérgombbal kattintva a multimédia-elemre, mindazon lehetőség az Ön rendelkezésére áll, mely a böngészőben is megtalálható, így például a kép elmentése, nyomtatása és beállítása háttérképnek.";

//-- Upload Media-page
$pgv_lang["help_uploadmedia.php"]		= "Az állományok feltöltése meglehetősen egyszerű, ezért itt csupán kiegészítő információkat közlünk.<br /><br /><b>Előnézeti képek:</b><br />Az előnézeti képek szélességét kb. 100 pixel körül érdemes megszabni. <br />Az állomány nevét változatlanul kell hagyni.<br /><br /><b>Feltöltés:</b><br />Az állományok automatikusan töltődnek fel a ../media könyvtárba (nagyméretű képek), illetve a  ../media/thumbs/ könyvtárba (az előnézeti képek).<br /><br /><center>További információért olvassa el a <a href=\"readme.txt\" target=\"_blank\"><b>Readme.txt</b></a> állományt.</center>";

//-- Anniversaries-page
$pgv_lang["help_calendar.php"]			= "Az Évforduló-naptár szerepe, hogy megmutassa Önnek az egyes napokhoz kötődő családi vagy személyes eseményeket (egy napra vagy egy hónapra vonatkoztatva).<br /><br />Az Évforduló-naptár számos hatékony eszközt foglal magába: Fejlett szűrőrendszerrel rendelkezik, mellyel Ön kiválaszthatja a megfelelő eseményeket.<br /><br />Az  <b>Adott napon</b> módban a keresés eredménye egy egyszerű lista vagy egy két oszlopos táblázat, melyek a megtalált személyeket és családokat mutatják be.<br /><br />Az <b>Adott hónapban</b> mód választásával egy <b>naptár</b> jelenik meg, feltüntetve az érintett személyeket és családokat.<br /><br />A lap tetején egy hivatkozásokat tartalmazó táblázat, valamint egy szöveges beviteli mező található, melyek segítségével Ön meghatározhatja a napot, hónapot, évet és eseményt, melyekhez kapcsolódó személyek érdeklik Önt.<br />Az aktuális napot, hónapot és eseményt pirossal emeltük ki.<br /><br />A nap és a hónap sorának végén két <b>\"gyorshivatkozást\"</b> találhat.<br />Ezek segítségével ön megjelenítheti az aktuális napra illetve hónapra vonatkozó listát, illetve naptárat.<br /><br />A listában és a naptárban látható nevek mindegyike kattintható, így ezeken át eljuthat az adott személy vagy család adatlapjára.<br /><br /><br />Ha szeretné, hogy a környezetérzékeny segítség elérhető legyen, győződjön meg arról, hogy a <b>Környezetérzékeny segítség megjelenítése</b> (a Segítség menüben) be van kapcsolva, és kattintson az érintett elem mögötti <b>?</b>-re.";
$pgv_lang["annivers_date_select_help"]		= "A \"vezérlő-táblázat\" felső sora a <b>nap-választó</b>.<br />Ennek szerepe magától értetődő: ezen keresztül tudja Ön kiválasztani a napot.<br />A választás eredménye attól függ, hogy Ön éppen az  \"Adot napon\" vagy az \"Adott hónapban\" módban van.<br /><br /><b>Adott napon</b> mód:<br />Ez esetben a program frissíti a képernyőt, és megjeleníti a kiválasztott naphoz tartozó listát.<br /><br /><b>Adott hónapban</b>:<br />Ha itt választ ki egy napot, a képernyő frissülni fog, de Ön továbbra is annak a hónapnak a naptárát látja, mint a választás előtt.<br />Mindez azért van, hogy Önnek legyen lehetősége egy másik hónap és/vagy év megjelölésére, mielőtt akár az <b>Adott napon</b> vagy az <b>Adott hónapban gombra</b> kattint.<br /><br />A sor végén talál egy <b>\"gyorshivatkozást\"</b> a mai dátummal.<br />Erre kattintva megtekintheti a mai napra vonatkozó listát, mégpedig \"Adott napon\" módban, függetlenül attól, hogy Ön esetleg az \"Adott hónapban\" módban volt éppen.";
$pgv_lang["annivers_month_select_help"]		= "A \"vezérlő-tábla\" középső sora a <b>hónap-választó</b>.<br />Hasonlóan a \"nap-választóhoz\", ennek az értelme is kézenfekvő: ezen keresztül tudja Ön kiválasztani a hónapot.<br /><br />And also like the Day Selector is the result of clicking on a month in the \"Day mode\" different from clicking on a month in the \"Month mode\".<br /><br />The <b>Day mode</b>:<br />In this mode, when you have clicked a month, the screen will refresh and the list will be displayed with the dates for the new selected month.<br />All other settings like day, year, and events will remain the same.<br /><br />The <b>Month mode</b>:<br />When you have the calendar on the screen and click a month in the \"Month\" row of the selector table, the calendar of the new month will be displayed.<br /><br />At the end of the Month row you will see the <b>\"Quick Link\"</b> with the current month.<br />Clicking that \"Quick Link\" will display the calendar of this month, no matter whether you are in the Month mode, or in the Day mode.";
$pgv_lang["annivers_year_select_help"]		= "Ezen beviteli mezővel változtathatja meg az évet az \"Adott napon\" listában, illetve az \"Adott hónapban\" naptárban.<br /><br />Ügyeljen arra, hogy az évszám begépelésével a képernyő tartalma nem frissül követlenül.<br />Mivel a beviteli mező nem hivatkozás, ezért vagy a <b>Adott napon</b> vagy pedig a  <b>Adott hónapban gombra</b> kell kattintania, hogy frissítse a tartalmat.";
$pgv_lang["add_name_help"]				= "GEDCOM ÁLLOMÁNYOK FELTÖLTÉSE ÉS HOZZÁADÁSA~<dl><dt>GEDCOM állományok feltöltése</dt><dd>Az állományok feltöltése online végezhető el.<br />Ön tetszőleges helyről végezheti el a feltöltést, ehhez nincs szüksége FTP-kapcsolatra.</dd><dt>GEDCOM állományok hozzáadása</dt><dd>Ha egy állomány már rendelkezésre áll az Ön GEDCOM-könyvtárában, akkor azt hozzáadhatja, nincs szüksége feltöltésre.<br />Bizonyos esetekben a hozzáadást kell alkalmazni feltöltés helyett, például túl nagy mérető állományok vagy feltöltési korlátozások miatt.</dd></dl>Mindkét módszer négy egyszerű lépésen keresztül végrehajtható, melyek csupán az első lépésben különböznek egymástól.";
$pgv_lang["gedcom_configfile_help"]		= "Ebben az állományban tárolódik a GEDCOM-állományokra vonatkozó összes alapvető beállítás.<br /><br />A GEDCOM-állományok adminisztrációs oldalán, a \"Konfigurációs állomány\" oszlopban találhatja meg az egyes konfigurációs állományok nevét és elérési útját.";
$pgv_lang["default_gedcom_help"]		= "Amennyiben Ön egynél több GEDCOM-állományt használ, akkor ebben a mezőben láthatja, melyik állomány számít <b>alapértelmezettnek</b>.<br /><br />Ezen állomány tartalmát láthatják azok a látogatók, akik még nem jelentkeztek be.<br /><br />A regisztrált felhasználók a maguk számára felülírhatják ezt a beállítást, ha a felhasználói adataik között módosítják azt.";
$pgv_lang["delete_gedcom_help"]			= "A PhpGedView mindig egy GEDCOM-állományból veszi át a megjelenített rekordokat. Mikor Ön a <b>Törlésre</b> kattint, a program minden, a GEDCOM-állományból származó adatot töröl.<br />Természetesen az érintett GEDCOM-állomány továbbra is abban a könyvtárban lesz megtalálható, ahová Ön feltöltötte. <br /><br />Így ha a későbbiekben újra dolgozni szeretne vele, nem kell ismét feltölteni, elegendő az <b>Új GEDCOM-állomány hozzáadása</b> opciót kiválasztania.<br /><br />Miután Ön a Törlésre kattintott, egy felugró ablakban kell <b>megerősítenie</b> ezt a döntést.";
//$pgv_lang["edit_gedcom_help"]			= "<b>Elnézést kérünk, de ennek az oldalnak a Segítsége még nem készült el.</b>";
$pgv_lang["add_gedcom_help"]			= "Az új GEDCOM-állomány hozzáadásának lehetősége abban az esetben működik, ha Ön már valamilyen <i>külső megoldással</i> - például <b>FTP-</b> vagy <b>hálózati kapcsolaton</b> keresztül - feltöltötte a szerverre a GEDCOM-állományt.<br />Amennyiben ez még nem történt meg, Önnek először fel kell töltenie az állományt, utána indíthatja el a hozzáadást.<br /><br />A folyamaton lépésről lépésre vezetjük Önt keresztül.";
$pgv_lang["add_new_gedcom_help"]		= "Biztosítjuk Önnek azt a lehetőséget is, hogy új GEDCOM-állományt hozzon létre a semmiből. <br /><br />Ez az eljárási is néhány lépésen keresztül elvégezhető: Ezek közül az első tér el a feltöltésnél és a hozzáadásnál megismert eljárástól, a többi lépés ismerős lesz Önnek.<dl><dt>1. lépés: Az új GEDCOM-állomány lenevezése</dt><dd>Gépelje be az új GEDCOM-állomány nevét, a '.ged' kiterjesztés nélkül. Az új állomány a beviteli mező alatt látható könyvtárba fog kerülni.<br />Kattintson a  <b>Hozzáadás</b> hivatkozásra.</dd><dt>2. lépés: Beállítások.</dt><dd>Ezt az oldalt Ön a GEDCOM-állományok beállításai kapcsán már megismerhette.</dd><dt>3. lépés: Ellenőrzés</dt><dd>Ez a lépés szintén ismerős lehet, ellenőrizzük az új GEDCOM-állományt.</dd><dt>4. lépés: Rekordok importálása</dt><dd>Mivel kezdetben egy rekordot kell importálni, a folyamat gyorsan le fog zajlani.</dd><dt>Létrehozás befejezése</dt><dd>Most már átléphet az ősfa oldalára, ahol láthatja az új GEDCOM-állomány első személyét. Kattintson a személy nevére és kezdje el feltölteni az adatait. Ezek után hozzáadhat új személyeket is, akik rokonságban állnak az első rögzített személlyel.</dd></dl>";
$pgv_lang["download_gedcom_help"]		= "Önnek rendelkezésére áll az a lehetőség, hogy honlapon megtalálható GEDCOM-állományokat letöltse.<br /><br />A \"GEDCOM-állomány letöltése\" oldalon eldöntheti, hogy átkonvertálja-e az állományt <b>UTF-8-as</b> kódolásból <b>ANSI (ISO-8859-1)-re</b>.<br />Hogy melyik formátum a megfelelő az Ön számára, az attól függ, milyen programmal kívánja feldolgozni a letöltés után.<br />Ellenőrizze a program dokumentációját, ha nem biztos a döntésben.";
$pgv_lang["edit_gedcoms_help"]			= "A GEDCOM-állományok adminisztrációs oldala az a központi lap, melyen ön elvégezheti az <b>aktuális</b> és az <b>új</b> GEDCOM-állományokra vonatkozó beállításokat.<br /><dl><b>AKTUÁLIS  GEDCOM-ÁLLOMÁNYOK</b><br /><dt>Az <b>aktuális GEDCOM-állományok</b> táblázatában Önnek a következőkre van lehetősége:</dt><dd>Törlés</dd><dd>Szerkesztés</dd><dl><dt>Diszkréciós beállítások</dt><dd>A diszkréciós beállítások szerkesztése is része ennek a táblázatnak, mivel minden GEDCOM-állománynak saját diszkréciós állománya van.</dd></dl><dd>Alapértelmezett GEDCOM beállítása</dd><dd>GEDCOM importálása</dd><dd>GEDCOM letöltése</dd><dt>Ezen kívül még a következő három oszlop található itt:</dt><dd>GEDCOM-állomány</dd><dd>GEDCOM-állomány címe</dd><dd>Konfigurációs állomány</dd></dl><dl><b>ÚJ GEDCOM-ÁLLOMÁNYOK</b><dt>Ezen az oldalon Önnek a következő lehetőségei vannak az <b>új</b> és/vagy a <b>már létező</b> GEDCOM-állomány hozzáadására.</dt><dd>Új GEDCOM-állomány hozzáadása</dd><dd>GEDCOM-állomány feltöltése</dd><dd>Új GEDCOM-állomány létrehozása</dd></dl><br />Ha szeretné, hogy a környezetérzékeny segítség elérhető legyen, győződjön meg arról, hogy a <b>Környezetérzékeny segítség megjelenítése</b> (a Segítség menüben) be van kapcsolva, és kattintson az érintett elem mögötti <b>?</b>-re.";
$pgv_lang["edit_config_gedcom_help"]	= "Minden, Ön által használt GEDCOM-állomány rendelkezik saját <b>konfigurációs állománnyal</b>.<br /><br />Ezen az űrlapon az olyan alapvető beállítások adhatók meg, mint a nyelv, naptár-formátum, e-mail lehetőségek stb.";
$pgv_lang["import_gedcom_help"]			= "Az esetek többségében a GEDCOM-állományok importálása csak egy lépése az olyan folyamatoknak, mint pl. GEDCOM-állományok hozzáadása és feltöltése.<br /><br />Ezen lépések egy logikai folyamat részét képezik és mindenképpen be kell őket fejezni, hogy Ön működőképes GEDCOM-állományt használhasson.<br />Ha Ön nem fejezi be a folyamatot, <b>figyelmeztető</b> üzenetet fog látni, mely szerint az importálás nem készült él, és kattintson a megjelölt hivatkozásra a GEDCOM-állomány (újra)importálásához.<br /><br /><b>Importálás</b><br />Abban az esetben, ha Ön vagy valamely másik felhasználó <b>online változtatást</b> végzett a GEDCOM-állományban, akkor azt újra kell importálni, hogy a módosítások rögzítésre kerüljenek.<br /><br />A konfigurációs beállítások ugyanakkor az állomány újraimportálásával nem változnak meg, viszont a létező adatokat a program felülírja.";
$pgv_lang["upload_gedcom_help"]			= "A \"GEDCOM-állomány hozzáadása\" opciótól eltérően nem szükséges, hogy az állomány már a szerveren legyen.<br /><br />Az 1. lépésben Önnek a számítógépen megtalálható állományt kell kiválasztania. Gépelje be a teljes elérési utat és az állomány bevét a beviteli mezőbe, vagy használja a <b>Böngészés</b> lehetőségét.<br /><br />A feltöltési folyamat egyes lapjain további segítséget kaphat e témakörben.";
$pgv_lang["random_media_ajax_controls_help"]	= "Itt állíthatja be, hogy a szabályozó gombok megjelenjenek-e a Véletlen Média dobozban.<br /><br />Ezekkel a gombokkal a felhasználó a következő elemre ugorhat, vagy elindíthatja a véletlen elemeket lejátszó vetítést. A vetítés úgy változtatja a doboz tartalmát, hogy nem tölti le előre az adatokat a szerverről, és nem tölti újra az oldalt.";
$pgv_lang["edit_add_unlinked_source_help"]	= "Itt új forrást adhat az adatbázishoz, a nélkül hogy másik rekordhoz kötné azt. Az új bejegyzés meg fog jelenni a források között, de addig nem jelenik meg a program ban sehol (pl. diagrammok), amíg nem hivatkozik rá másik bejegyzés.";
$pgv_lang["random_media_start_slide_help"]			= "Automatikusan induljon-e el a képbemutató ha az odal betöltődik.<br /><br />A képbemutató a doboz tartalmát változtatja, a nélkül, hogy a előre betöltené az adatokat, vagy hogy az egész oldalt újratöltené.";

//-- Edit Config
$pgv_lang["help_editconfig.php"]		= "Ezen az oldalon kell Önnek elvégeznie a program általános beállítását, miután elvégezte a PhpGedView telepítését, és első alkalommal futtatja a programot.<br />Ajánlott elolvasni a <a href=\"readme.txt\" target=\"_blank\">readme.txt</a> fájlt, mielőtt folytatja a PhpGedView beállítását.<br /><br /><br /><br />Mivel ezek a beállítások <b>általánosak</b>, ezért az egész programot és az összes GEDCOM-állományt érintik.<br />Ugyanakkor az egyes GEDCOM-állományokra vonatkozó beállításokat is van lehetősége elvégezni.<br />Ennek érdekében kattintson az űrlap fölött található hivatkozásra.<br />Minden más esetben az erre vonatkozó hivatkozást megtalálja a a MyGedView Portál menüjében.";
$pgv_lang["help_birthlist.xml"]		= "Ezzel a jelentéssel Őn kitudja listázni azokat a személyeket akik egy bizonyos időben vagy helyen született.";

//-- Help Contents
$pgv_lang["help_contents_head_help"]		= "<b>SEGÍTSÉG TARTALOMJEGYZÉK</b>";
$pgv_lang["help_contents_gedcom_info"]		= "GEDCOM infó";
$pgv_lang["help_contents_gedcom_places"]	= "Helyszínek a GEDCOM -ban";

//-- Admin Help Contents Items
$pgv_lang["admin_help_contents_head_help"]	= "<b>SEGÍTSÉG TARTALOMJEGYZÉK<br /><br />ADMINISZTRÁTOR SEGÍTSÉG ELEMEI</b> hozzá lettek adva a lista elejéhez.";
$pgv_lang["ah2_help"]				= "_PhpGedView Konfiguráció";
$pgv_lang["ah3_help"]				= "_GEDCOM: Hozzáadás vs Feltöltés";
$pgv_lang["ah4_help"]				= "_GEDCOM: Konfiguráció állomány";
$pgv_lang["ah5_help"]				= "_GEDCOM: Alap";
$pgv_lang["ah6_help"]				= "_GEDCOM: Törlés";
$pgv_lang["ah7_help"]				= "_GEDCOM: Hozzáadás";
$pgv_lang["ah8_help"]				= "_GEDCOM: Új";
$pgv_lang["ah9_help"]				= "_GEDCOM: Letöltés";
$pgv_lang["ah10_help"]				= "_GEDCOM: Adminisztráció oldal";
$pgv_lang["ah11_help"]				= "_GEDCOM: Konfiguráció";
$pgv_lang["ah12_help"]				= "_GEDCOM: Import";
$pgv_lang["ah13_help"]				= "_GEDCOM: Feltöltés";
$pgv_lang["ah14_help"]				= "_GEDCOM: Érvényesítés";
$pgv_lang["ah15_help"]				= "_GEDCOM: Átírás ANSI -ról UTF-8 -ra";
$pgv_lang["ah16_help"]				= "_GEDCOM: Bizalmas beállítások";
$pgv_lang["ah17_help"]				= "_Felhasználó Adminisztrálás";
$pgv_lang["ah18_help"]				= "_Adminisztrálás";
$pgv_lang["ah19_help"]				= "_GEDCOM: Média Eszköz";
$pgv_lang["ah20_help"]				= "_GEDCOM: Személy azonosító változtatása";
$pgv_lang["ah21_help"]				= "_Nyelvi eszközök";
// 22 is in the help_text_vars.php
$pgv_lang["ah23_help"]				= "_Támogatott nyelvek konfigurációja";
$pgv_lang["ah26_help"]				= "_GYIK lista: Szerkesztés";
$pgv_lang["help_faq.php"]			= "#pgv_lang[text_faq_help]#";
$pgv_lang["hs_title_help"] 			= "<center>~Keresési Segítség~</center><br />#pgv_lang[hs_intro]#<br /><br />#pgv_lang[hs_keyword_advice]#<br /><br />#pgv_lang[hs_searchhow_advice]#<br /><br />#pgv_lang[hs_searchin_advice]#";

//-- Index-page Portal

$pgv_lang["edit_ROMN_help"]			= "Egyes kultúrákban, szokás hogy a tradicionális karakterekkel írt név mellett, legyen egy olyan verziójú név is, amely egyéb, csak latin karaktereket használó nyelvekben is használható, mint például Angol.<br /><br />Ha az erdeti név mezőben az eredeti formában kívánja megadni a nevet például Héber, Görög, Orosz, Kínai vagy Arab nyelvek esetében, akkor ebben a mezőben megadhatja a nevet Latin karakterekkel is. Mind a két verzió meg fog jelenni a listákban és a diagrammokban.<br /><br />Bár a mező neve \"Romanizált\", a mező nem csak Latin karaktereket tartalmazhat. Ez a Japán nevek esetében lehet hasznos, ahol a neveknél 3 fajta betű is előfordulhat.";
$pgv_lang["edit__HEB_help"]			= "Egyes kultúrákban, szokás hogy a tradicionális karakterekkel írt név mellett, legyen egy olyan verziójú név is, amely egyéb, csak latin karaktereket használó nyelvekben is használható, mint például Angol.<br /><br />Ha az erdeti név mezőben az eredeti formában kívánja megadni a nevet például Héber, Görög, Orosz, Kínai vagy Arab nyelvek esetében, akkor ebben a mezőben megadhatja a nevet Latin karakterekkel is. Mind a két verzió meg fog jelenni a listákban és a diagrammokban.<br /><br />Bár a mező neve \"Héber\", nem csak Héber karaktereket tartalmazhat.";
$pgv_lang["edit_ABBR_help"]			= "Ez a mező a cím rövidített változatát tartalmazza. Kapcsolatban áll a cím mezővel a források közül. Alapértelmezés szerint a PGV először a címet használja, majd a rövidítést.<br /><br />A GEDCOM 5.5 -ös specifikáció szerint, \"ez a mező rövidítést tartalmaz a rendezéshez, kereséshez és a forrás bejegyzések eléréséhez (pg 62)\"<br /><br />A PhpGedView-ban ez a mező elhagyható, bár egyéb családfakutató programokban szükséges lehet.";
$pgv_lang["link_remote_help"]       = "Ezen a formon hivatkozhat különböző emberekre különböző oldalakon levő PhpGedView adatbázisokból.<br /><br />Egy ilyen kapcsolat hozzáadásához, először ki kell választania a kapcsolat típusát, majd a PhpGedView-ban korábban beállított oldalt (vagy újat vehet fel), és végül meg kell adnia a hivatkozott személy azonosítóját. Ezután a PhpGedView automatikusan letölti a szükséges információkat a kiválasztott oldalról. A letöltött adat, <u>nem</u> válik a saját családfakutató adatbázis részévé; megmarad a eredeti oldalon, a rá hivatkozó oldalakon csak bejegyzések lesznek a távoli személyre hivatkozva.<br /><br />Az oldalakon minden egyes elemhez kaphat segítséget a mellette lévő Segítség-re kattintva. Bővebb információt az online Angol oldalon kaphat:<a href=\"http://wiki.phpgedview.net/en/index.php/How_to_Remote_Link\" target=\"_blank\">http://wiki.phpgedview.net/en/index.php/How_to_Remote_Link</a>.";
$pgv_lang["link_remote_rel_help"]	= "Itt adhatja meg, hogy a távoli személy milyen kapcsolatban van a kiválasztottal. Például kiválasztva hogy <i>Apa</i>, azt adjuk meg, hogy a távoli személy a nálunk kiválasztott személy apja.";
$pgv_lang["link_remote_location_help"]	= "Ez az opció arra vonatkozik, hogy ha a személy akire hivatkozik, ugyan azon az oldalon van, de egy másik családfakutató adatbázisban, vagy egy másik oldalon az Interneten.<br /><br />Ha ugyan azon az oldalon van, meg kell adnia a keresett személy azonosítóját.<br /><br />Távoli oldal esetén, meg kell adnia az URL-t, az adatbázis azonosítót, és a távoli személy azonosítóját.";
$pgv_lang["link_remote_site_help"]	= "Itt kell megadnia azokat a paramétereket, amelyek szükségesek ahhoz, hogy olyan távoli kiszolgálóhoz kapcsolódjon, ahol bizonyos bejegyzésekre szeretne hivatkozni. Választhat már korábban beállított oldalak közül, vagy megadhatja a következő paramétereket új felvételekor: #pgv_lang[label_site_url2]# , Adatbázis azonosítószáma .<br /><br />. A <b>#pgv_lang[label_site_url2]#</b> mezőben a távoli szerver leíró fájljához (WSDL) tartozó elérési útvonalat (URL) adhatja meg, amely megmondja a PhpGedView-nek, hogy a távoli adatokat hogyan érje el. Egy távoli PhpGedView oldal esetében, az URL a WSDL fájlra valahogy így néz ki: <u>http://www.remotesite.com/phpGedView/genservice.php?wsdl</u><br /><br />A <b>Adatbázis azonosítószáma</b> mezőben egyedi adatbázis azonosítót adhat meg, amennyiben erre szükség van. PhpGedView oldalak esetében ez a GEDCOM fájl neve.<br /><br />A <b>Felhasználónév</b> és a <b>Jelszó</b> mezőkre akkor van szükség, ha az adatbázis megköveteli.<br /><br /><i>Megejgyzés: a távoli PhpGedView oldalak verziószáma minimum 4.0 kell hogy legyen, ahhoz hogy ez a funkció működjön.</i>";
$pgv_lang["link_gedcom_id_help"]	= "Ebben a részben az alternatív azonosítót adhatja meg egy személyhez, akire hivatkozik.";
$pgv_lang["link_person_id_help"]	= "Ebbe a mezőbe írja be a személy azonosítóját akihez kapcsolni akar (pl. I100).";
$pgv_lang["edit_SEX_help"]			= "#pgv_lang[edit_sex_help]#";
$pgv_lang["edit_ADDR_help"]			= "Írjon be címet a mezőbe, épp úgy mint ahogyan egy borítékra írná.<br /><br />Üresen hagyható.";
$pgv_lang["edit_SPFX_help"]			= "Írjon be, vagy válasszon a listából a névhez előtagot, amely része a vezetéknévnek. Például: <b>von</b> Braun, <b>van der</b> Kloot, <b>de</b> Graaf, stb.";
$pgv_lang["edit_PHON_help"]			= "Adjon meg telefonszámot az országkóddal együtt.<br /><br />Üresen hagyható. Például egy németországi telefonszám így néz ki: +49 25859 56 76 89, USA-ban vagy Kanadában pedig így: +1 888 555-1212. Magyarország országkódja: 36";
$pgv_lang["edit_FAX_help"]			= "Adjon meg FAX számot országkóddal együtt.<br /><br />Üresen hagyható. Például egy németországi fax szám így néz ki: +49 25859 56 76 89, USA-ban vagy Kanadában pedig így: +1 888 555-1212. Magyarország országkódja: 36";
$pgv_lang["edit_EMAIL_help"]		= "Adjon meg email címet.<br /><br />Például:: <b>name@hotmail.com</b>. Üresen hagyható.";
$pgv_lang["edit_URL_help"]			= "Adja meg az URL címet a http:// előtaggal együtt<br /><br />Például: <b>http://www.phpgedview.net/</b>.";
$pgv_lang["edit_add_unlinked_person_help"]	= "Ezt a formot arra használhatja, hogy olyan személyeket vigyen fel, akikre nincs hivatkozás.<br /><br />Amikor egy ilyen személyt ad a családfához, azok nem fognak kapcsolódni senkihez, amíg össze nem kapcsoljuk valakivel. Később is összekapcsolhat személyeket a Közeli családtagok menüpontot választva a(z) Személyes adatok oldalon.";
$pgv_lang["edit_NAME_help"]			= "#pgv_lang[edit_name_help]#";
$pgv_lang["edit_GIVN_help"]			= "#pgv_lang[edit_given_name_help]#";
$pgv_lang["edit_SURN_help"]			= "#pgv_lang[edit_surname_help]#";
$pgv_lang["edit_NSFX_help"]			= "#pgv_lang[edit_suffix_help]#";
$pgv_lang["register_gedcomid_help"]	= "Az adatbázisban lévő minden személynek, saját egyedi azonosítója van az oldalon. Ha tudja ezt, itt adhatja meg. Ha nem tudja, vagy az privát és nem látja, adjon meg elegendő információt a Megjegyzés mezőben, hogy segítse az adminisztrátort az azonosítója megtalálásában.";
$pgv_lang["firstname_i_help"]		= "A választott vezetéknévhez több mint #GLOBALS[SUBLIST_TRIGGER_I]# személy tartozik.<br /><br />Ahhoz hogy megtalálja a keresett személyt, a lista több kisebb részre van felosztva, a személy keresztneve alapján. Ez a keresztneves abc lista, hasonló a vezetékneveshez.<br /><ul><li>Kattintson egy betűre, hogy lássa az összes vezetéknevet, ami azzal a betűvel kezdődik.</li><li>Válassza a <b>(ismeretlen)</b>-t az összes olyan személy listájához, akiknek nem ismert a vezetékneve.</li><li>.A <b>Mind</b>-t választva, az előzőleg kiválasztott vezetéknévhez tartozó összes személy listázásra kerül.</li></ul>Mivel sok név lehet, ezért a listázás sokáig tarthat.";
$pgv_lang["reorder_families_help"]		= "A családok a Közeli családtagok fülön, olyan sorrendben jelennek meg, ahogy a személy GEDCOM bejegyzésében jelennek meg. A családok nem a házasság időpontja szerint vannak rendezve, mert gyakran az időpont nem ismert, de a sorrendjük <u>igen</u><br /><br />Itt lehet beállítani a családok sorrendjét, hogy hogyan jelenjenek meg a Közeli családtagok fülön. Ha a családokat a házassági dátum alapján szeretné rendezni, az erre való gombbal megteheti.";
$pgv_lang["show_spouse_help"]			= "Ez a grafikon alapértelmezésben nem mutatja a leszármazott házastársát, mert úgy nehezebb a grafikont olvasni és megérteni. Ezzel az opcióval bekapcsolható a házastársak mutatása a grafikonon.";
$pgv_lang["edit_RELA_help"]		= "Válassza a ki a kapcsolat típusát a listából. A <b>Keresztapa</b> azt jelenti:<i>Ez a tag a jelenlegi személy keresztapja</i>.";
$pgv_lang["edit_ASSO_help"]		= "Írja be a társ GEDCOM ID -t.";
$pgv_lang["edit_CEME_help"]		= "Adja meg a temetőt, vagy egyéb helyet ahol a személyt eltemették.";
$pgv_lang["edit_NOTE_help"]		= "A jegyzet mező szabadon szerkeszthető szövegmező, amely megjelenik a Tények részleteinél az oldalon.";
$pgv_lang["edit_TIME_help"]		= "Adja meg az esemény időpontját 24 órás formátumban, nullákkal kiegészítve. Az éjfél: 00:00. Például: 04:50 vagy 13:00 vagy 20:30.";
$pgv_lang["edit_NCHI_help"]		= "Adja meg a gyerekek számát ehhez a személyhez vagy családhoz. Ez a mező nem kötelező";
$pgv_lang["remember_me_help"]	= "Ezt a jelölőnégyzetet bejelölve, belépéskor a PhpGedView emlékezni fog Önre, így nem kell újra bejelentkeznie. Ekkor egy süti kerül eltárolásra az Ön gépén, amit a legközelebbi bejelentkezéskor az azonosításhoz használ a rendszer.<br /><br />Legközelebbi látogatáskor hozzáférhet privát információkhoz, hozzáférhet felhasználói oldalakhoz, de adminisztratív feladatokhoz meg kell adnia a felhasználói nevét és jelszavát újra.<br /><br /><b>Ne jelölje be ezt akkor, ha publikus helyről jelentkezik be, vagy megosztja a gépét másokkal; így bárki beléphet az oldalra, mintha Ön lenne az.</b>";
$pgv_lang["download_zipped_help"]	= "Ha ezt az opciót bejelöli, akkor a GEDCOM fájl letöltés előtt ZIP formátumban kerül tömörítésre. Így a mérete jelentősen lecsökkenhet, de így használat előtt, egy kompatibilis kitömörítő programmal ki kell azt csomagolni (Pl.: WinZIP).<br /><br />Ez hasznos lehet nagy GEDCOM fájlok letöltésekor. Túl nagy fájlok esetén lehetséges, hogy a letöltéskor időtúllépés lép fel, és így hibás fájl töltődik le. A ZIP opció a letöltési időt kb. 75%-al csökkentheti.";
$pgv_lang["remove_tags_help"]	= "Ezzel kapcsolóval, a speciális címkék távolíthatók el, amelyeket a PhpGedView fűzött a rekordokhoz.<br /><br />A PhpGedView által használt címkékben a <b>_PGVU</b> rész arra vonatkozik, hogy ki módosította a rekordot utoljára online, a <b>_THUM</b> cimke pedig azt jelzi, hogy a kép kisképként is használható. <br /><br />Ezek a saját címkék hibákat okozhatnak, ha a GEDCOM fájlt bizonyos családfakutató programokban szeretnénk használni.";
$pgv_lang["utf8_ansi_help"]		= "Az interneten való optimális megjelenéshez, a PhpGedView az UTF-8 -as karakterkódolást használja. Létezik néhány családfakutató program például a Family Tree Maker, amely nem támogatja a GEDCOM fájlok importálását UTF-8 -as kódolásban. Ezt a jelölőnégyzetet bejelölve, az <b>UTF-8</b>-as kódolásból <b>ANSI (ISO-8859-1)</b> -as kódolás lesz. <br /><br />Az hogy milyen kódolásra van szüksége, az attól függ, hogy milyen programmal szeretné használni a letöltött GEDCOM fájlt. Ha nem biztos benne, akkor tanulmányozza annak a programnak a dokumentációját.<br /><br />Ahhoz hogy a speciális karakterek megmaradjanak, ajánlott az UTF-8 -as kódolást használni, és ezt a programban használni. Ha szükséges, olvassa el a dokumentációt, vagy lépjen kapcsolatba a program készítőjével, vagy viszonteladójával.";
$pgv_lang["register_comments_help"]	= "Ebben a mezőben írhatja meg az adminisztrátornak, hogy miért szeretne az oldalhoz hozzáférést, és hogy milyen kapcsolatban van ezzel a családfakutató oldallal. Ide egyéb közlendőt is írhat az adminisztrátornak.";
$pgv_lang["context_help"]			= "Több segítség, az elem melletti <b>?</b> -re kattintva érhető el.";
$pgv_lang["edit_PEDI_help"]			= "Ez a mező, a gyerek kapcsolatát írja le a családjával. Lehetséges értékek: <ul><li><b>ismeretlen</b>&nbsp;&nbsp;&nbsp;nem meghatározható. Ekkor a Felmenő rokonság mező nem kerül az adatbázisba.<br /><br /></li><li><b>Született</b>&nbsp;&nbsp;&nbsp;a gyerek a családban született.<br /><br /></li><li><b>Örökbefogadott</b>&nbsp;&nbsp;&nbsp;a gyereket a család örökbefogadta. Ez <i>nem</i> azt jelenti, hogy nincs vérszerinti kapcsolat a gyerek és a család között; azt jelenti, hogy a család örökbefogadta a gyereket valahány évvel a születése után.<br /><br /></li><li><b>Nevelő</b>&nbsp;&nbsp;&nbsp;a szülők nevelőszülei a gyereknek. Általában ilyenkor nincs vér szerinti kapcsolat.<br /><br /></li><li><b>Befogadás</b>&nbsp;&nbsp;&nbsp;törvényesítés. Ha a házasság a gyerek születése után történik.";
$pgv_lang["edit__MARNM_help"]		= "Írja be a személy házasult nevét, olyan formában, mint ami a név mezőre vonatkozik. Ez a mező nem kötelező.<br /><br />Például ha Mary Jane Brown házasult John White, beírhatja(az idézőjelek nélkül) hogy <ul><li>Amerikai használat:&nbsp;&nbsp;\"Mary Jane Brown /White/\"</li><li>Európai használat:&nbsp;&nbsp;\"Mary Jane /White/\"</li><li>Alternatív Európai használat:&nbsp;&nbsp;\"Mary Jane /White-Brown/\" vagy \"Mary Jane /Brown-White/\"</li></ul>Ezt csak akkor tegye, ha Mary Brown felvette az új nevét házasság után. Néhány helyen, mint például Quebec (Canada), nem lehet a nevet így megváltoztatni.<br /><br />Van olyan, hogy a férfiak is megváltoztatják a nevüket házasság után, és vagy kötőjelesen, vagy teljesen felveszik a feleség vezetéknevét.";
$pgv_lang["no_update_CHAN_help"] 	= "Az adminisztrátoroknak időnként át kell nézniük, és korrigálniuk kell a felhasználók által beküldött adatokat. Például lehet hogy ki kell javítani a helység megjelölést, hogy tartalmazza az országot is. Amikor az adminisztrátorok ilyen módosításokat végeznek, az eredeti információk a változtatással lecserélődnek. Egyes esetekben ez nem kívánt.<br /><br />Amikor ezt az opciót választjuk, a PhpGedView megőrzi az eredeti változtatás információit a helyett hogy rögtön kicserélné az új információkkal. Így az adminisztrátor módosíthatja vagy törölheti a eredeti CHAN cimkét.";
$pgv_lang["edit_SOUR_EVEN_help"]	= "Minden forrásbejegyzés meghatározott eseményre utal, bizonyos időhatárok között és hely hatókörben. Például a Census (népszámlálás) bejegyzés vonatkozhat népszámlálásra, születésre, házasságra és elhalálozásra.<br /><br />Válassza ki a listából, hogy mely események tartoznak a forráshoz. A dátum, tartományra vonatkozik úgy mint <i>1900-tól 1910-ig</i>. A hely hatókör, azokra az alacsonyabb rendű helyekre vontakozik, amelyek a forrásban vannak megnevezve. Például a \"Csongrád, Magyarország\" forrás, hatókörként használható olyan eseményekhez, amelyek Csongrád megye különböző városaiban történtek. \"Bács-Kiskun, Csongrád, Magyarország\" pedig arra vonatkozhat, ha a város lehetett Bács-Kiskun megyében vagy Csongrád megyében.";
$pgv_lang["cache_life_help"]		= "A teljesítmény növelése érdekében a PhpGedCom üdvözlő oldala cache fájlként kerül tárolásra. Azt hogy ez a fájl milyen gyakran frissüljön, beállítható. <br /><br /><ul><li><b>-1</b> jelentése, hogy a fájl nem frissül automatikusan. A friss adatokhoz a cache fájlokat kell üríteni. </li><li><b>0</b> (nulla) jelentése, hogy a lap nem tárolódik el, és valahányszor a főoldal töltődik be, az oldal frissül. Ez a beállítás automatikus olyan részekhez mint például Bejelentkezett felhasználók blokk vagy Véletlen média blokk.</li><li><b>1</b> (egy) jelentése, hogy a cache fájl naponta frissül, <b>2</b> esetén 2 naponta, <b>7</b> esetén hetente, stb.</li></ul>";
$pgv_lang["clear_cache_help"]		= "A teljesítmény növeléséhez, az üdvözlő oldalon lévő dobozok cache fájlban tárolódnak az index könyvtárban. A legtöbb doboz esetében, ezek naponta frissülnek, de ezek kézzel is frissíthetők.<br /><br />Ezzel a gombbal frissítheti ezeket a cache fájlokat, amennyiben szükséges.";
$pgv_lang["import_options_help"] 	= "Több opciót is választhat, amikor GEDCOM-ot importál.";
$pgv_lang["verify_gedcom_help"]	= "Itt választhat, hogy folytatja a GEDCOM feltöltését és importálását, vagy megszakítja azt.";
$pgv_lang["add_gedcom_instructions"]= "Adjon fájlnevet az új GEDCOM-hoz. Az új GEDCOM fájl az index könyvtárban jön létre: #INDEX_DIRECTORY#";
?>
