htmlplus_block_keyword|Keyword Example Page
This template is not intended to be viewed by ordinary users.  It is intended to serve as documentation, listing each variable built into the Advanced HTML block, together with the resulting text when a reference to this variable is embedded in the HTML code supplied to the Advanced HTML block.<br />
<table border="1">
<thead>
<tr><th>Variable</th><th>Resultant text</th></tr>
</thead>
<tbody>
<tr><td align="right" valign="top" style="padding:3px">commonSurnames</td><td>#commonSurnames#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalIndividuals</td><td>#totalIndividuals#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalIndividualsPercentage</td><td>#totalIndividualsPercentage#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalFamilies</td><td>#totalFamilies#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalFamiliesPercentage</td><td>#totalFamiliesPercentage#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalSources</td><td>#totalSources#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalSourcesPercentage</td><td>#totalSourcesPercentage#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalOtherRecords</td><td>#totalOtherRecords#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalOtherPercentage</td><td>#totalOtherPercentage#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalSurnames</td><td>#totalSurnames#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalSexMales</td><td>#totalSexMales#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalSexMalesPercentage</td><td>#totalSexMalesPercentage#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalSexFemales</td><td>#totalSexFemales#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalSexFemalesPercentage</td><td>#totalSexFemalesPercentage#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalSexUnknown</td><td>#totalSexUnknown#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalSexUnknownPercentage</td><td>#totalSexUnknownPercentage#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalEvents</td><td>#totalEvents#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalEventsBirth</td><td>#totalEventsBirth#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalEventsDeath</td><td>#totalEventsDeath#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalEventsMarriage</td><td>#totalEventsMarriage#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalEventsOther</td><td>#totalEventsOther#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalUsers</td><td>#totalUsers#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalMedia</td><td>#totalMedia#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">firstEvent</td><td>#firstEvent#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">firstEventYear</td><td>#firstEventYear#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">firstEventType</td><td>#firstEventType#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">firstEventName</td><td>#firstEventName#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">firstEventPlace</td><td>#firstEventPlace#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">lastEvent</td><td>#lastEvent#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">lastEventYear</td><td>#lastEventYear#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">lastEventType</td><td>#lastEventType#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">lastEventName</td><td>#lastEventName#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">lastEventPlace</td><td>#lastEventPlace#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">firstBirth</td><td>#firstBirth#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">firstBirthYear</td><td>#firstBirthYear#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">firstBirthName</td><td>#firstBirthName#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">firstBirthPlace</td><td>#firstBirthPlace#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">lastBirth</td><td>#lastBirth#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">lastBirthYear</td><td>#lastBirthYear#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">lastBirthName</td><td>#lastBirthName#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">lastBirthPlace</td><td>#lastBirthPlace#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">firstDeath</td><td>#firstDeath#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">firstDeathYear</td><td>#firstDeathYear#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">firstDeathName</td><td>#firstDeathName#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">firstDeathPlace</td><td>#firstDeathPlace#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">lastDeath</td><td>#lastDeath#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">lastDeathYear</td><td>#lastDeathYear#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">lastDeathName</td><td>#lastDeathName#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">lastDeathPlace</td><td>#lastDeathPlace#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">longestLife</td><td>#longestLife#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">longestLifeAge</td><td>#longestLifeAge#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">longestLifeName</td><td>#longestLifeName#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">longestLifeMale</td><td>#longestLifeMale#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">longestLifeMaleAge</td><td>#longestLifeMaleAge#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">longestLifeMaleName</td><td>#longestLifeMaleName#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">topTenOldestMale</td><td>#topTenOldestMale#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">topTenOldestMaleList</td><td>#topTenOldestMaleList#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">averageLifespanMale</td><td>#averageLifespanMale#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">longestLifeFemale</td><td>#longestLifeFemale#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">longestLifeFemaleAge</td><td>#longestLifeFemaleAge#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">longestLifeFemaleName</td><td>#longestLifeFemaleName#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">topTenOldestFemale</td><td>#topTenOldestFemale#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">topTenOldestFemaleList</td><td>#topTenOldestFemaleList#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">averageLifespanFemale</td><td>#averageLifespanFemale#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">topTenOldest</td><td>#topTenOldest#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">topTenOldestList</td><td>#topTenOldestList#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">averageLifespan</td><td>#averageLifespan#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalLiving</td><td>#totalLiving#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalLivingPercentage</td><td>#totalLivingPercentage#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalDeceased</td><td>#totalDeceased#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalDeceasedPercentage</td><td>#totalDeceasedPercentage#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalMortalityUnknown</td><td>#totalMortalityUnknown#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">totalMortalityUnknownPercentage</td><td>#totalMortalityUnknownPercentage#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">largestFamily</td><td>#largestFamily#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">largestFamilySize</td><td>#largestFamilySize#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">largestFamilyName</td><td>#largestFamilyName#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">topTenLargestFamily</td><td>#topTenLargestFamily#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">topTenLargestFamilyList</td><td>#topTenLargestFamilyList#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">averageChildren</td><td>#averageChildren#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">gedcomFilename</td><td>#gedcomFilename#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">gedcomID</td><td>#gedcomID#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">gedcomTitle</td><td>#gedcomTitle#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">gedcomHighlight</td><td>#gedcomHighlight#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">gedcomHighlightLeft</td><td>#gedcomHighlightLeft#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">gedcomHighlightRight</td><td>#gedcomHighlightRight#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">gedcomCreatedSoftware</td><td>#gedcomCreatedSoftware#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">gedcomCreatedVersion</td><td>#gedcomCreatedVersion#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">gedcomDate</td><td>#gedcomDate#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">gedcomUpdated</td><td>#gedcomUpdated#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">contactWebmaster</td><td>#contactWebmaster#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">contactGedcom</td><td>#contactGedcom#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">serverDate</td><td>#serverDate#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">serverTime</td><td>#serverTime#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">serverTime24</td><td>#serverTime24#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">serverTimezone</td><td>#serverTimezone#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">browserDate</td><td>#browserDate#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">browserTime</td><td>#browserTime#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">browserTime24</td><td>#browserTime24#</td></tr>
<tr><td align="right" valign="top" style="padding:3px">browserTimezone</td><td>#browserTimezone#</td></tr>
</tbody>
</table>
