<?php
/**
 * Catalan FAQ texts
 *
 * phpGedView: Genealogy Viewer
 * Copyright (C) 2002 to 2009  PGV Development Team.  All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @author Antoni Planas i Vilà
 * @package PhpGedView
 * @subpackage Languages
 * @version $Id$
 */

if (!defined('PGV_PHPGEDVIEW')) {
	header('HTTP/1.0 403 Forbidden');
	exit;
}

$faqlist["FAQ_000_head"] = "\"FAQ-PMF\": N'HE SENTIT PARLAR PERÒ, QUÈ ÉS?";
$faqlist["FAQ_000_body"] = "<b>FAQ</b> és l'acrònim anglès de <b>F</b>requently <b>A</b>sked <b>Q</b>uestion. (PMF, Preguntes Més Freqüents, en català) <br /><br />És una llistat de preguntes (juntament amb llurs respostes) que es fan sovint. Han sigut recopilades per l'equip del PhpGedView i es va revisant sovint.";

$faqlist["FAQ_010_head"] = "BENVINGUTS A LES PMF (Preguntes Més Freqüents) DE #GLOBALS[GEDCOM_TITLE]# ";
$faqlist["FAQ_010_body"] = "Els membres de la família de #GLOBALS[GEDCOM_TITLE]# volem aprofitar aquesta oportunitat per donar la benvinguda a la genealogia a tots els nostres familiars i animar-vos a que us piqui el cuc d'investigar sobre els vostres avantpassats. Pot esdevenir una tasca d'amor -i odi- doncs requereix una dedicació enorme. Però la recompensa és igual d'enorme. Us oferim l'oportunitat de gaudir de la genealogia mitjançant l'ús de <a href=\"http://www.phpgedview.net\" target=\"_blank\">PhpGedView</a>, creat pel talent en programació de John Finlay i el seu equip PGV - Un meravellós programa de genealogia fruit de la tecnologia de Codi Font Obert.";

$faqlist["FAQ_015_head"] = "QUINA ÉS LA DIFERÈNCIA ENTRE AQUEST ARBRE PhpGedView I ALTRES ARBRES TEXTUALS I DINÀMICS?";
$faqlist["FAQ_015_body"] = "Els arbres textuals i els dinàmics es presenten de diverses formes, però cap d'ells us permet configurar-lo, canviar-lo o actualitzar-lo. Solament l'administrador de webs pot fer-hi actualitzacions.<br /><br />El PhpGedView en canvi, és un arbre interactiu. Qualsevol de la família, en tota l'extensió de l'arbre, pot modificar, afegir i fer canvis de les seves branques properes. (Per a poder fer-ho cal registrar-se però prèviament).";

$faqlist["FAQ_017_head"] = "QUINES SON LES CARACTERÍSTIQUES ESPECIALS D'AQUEST ARBRE?";
$faqlist["FAQ_017_body"] = "Amb PhpGedView podeu:<ul><li>Conservar la privadesa de la gent viva; l'administrador del lloc web determina el que podeu veure.</li><li>Gaudiu de més possibilitats per veure l'arbre: com diferents gràfics, informes o llistes.</li><li>És un arbre participatiu, amb el permís de l'administrador cada ú pot col·laborar en actualitzar-lo.</li></ul>";

$faqlist["FAQ_020_head"] = "NECESSITO UN COMPTE PER ACCEDIR-HI? SI ÉS AIXÍ, COM PUC FER-HO PER ACONSEGUIR-LO?";
$faqlist["FAQ_020_body"] = "Podem dir \"Benvingut parent\"?<br /><br /><b>NOTA: a #GLOBALS[GEDCOM_TITLE]#  NO CAL ENREGISTRAR-SE per disposar d'accés a dades de persones difuntes. Tanmateix, per col·laborar i veure esdeveniments de persones presumptament vives, us cal enregistrar-vos i informar-nos sobre el vostre parentiu.</b>";
$faqlist["FAQ_020_body2"] = "Els usuaris enregistrats veuen els noms de totes les persones vives del lloc, dades detallades de les difuntes i llurs parents propers.<br /><br />Els usuaris que no hi tingui cap mena de parentiu veuen solament els noms de les persones vives i dades detallades dels difunts.";
$faqlist["FAQ_020_body3"] = "<ol><li>Els enregistrats cal que siguin parents, llunyans en alguns cassos, o emparentats d'alguna manera amb algú que ja surt o que podria sortir al nostre lloc;</li><li>Cal que estiguin disposats a visitar i contribuir regularment al nostre lloc, primerament fornint-nos informació personal i sobre els seus parents directes. I posteriorment amb modificacions, increment, ampliació i addicions de les nostres dades existents;</li><li>També cal que es comprometin a preservar la privadesa de les dades de totes les persones vives del lloc i, com s'ha dit abans, contribuir amb llur informació personal. Els incompliments poden comportar l'acabament dels privilegis d'accés i causar accions legals. Ens prenem molt seriosament la possibilitat de falsificació de personalitat o d'ús indegut de la informació. Per a més detalls, mireu-vos més avall la nostra secció de Privadesa.</li></ol>Si esteu qualificat per enregistrar-vos i accepteu complir aquestes senzilles normes i procediments, tingueu a be enregistrar-vos omplint aquest <b><a target=\"_blank\" href=\"/phpGedView/login_register.php?action=register\">formulari de registre</a></b> que trobareu dins del lloc. Assegureu-vos d'emplenar el petit qüestionari on detallareu la mena de parentiu amb les persones d'aquest lloc i on també declarareu clarament manifestareu estar d'acord i acceptar les nostres normes i procediments.  Estudiarem i considerarem la vostra sol·licitud.";
$faqlist["FAQ_020_body4"] = "L'autorització de un nou compte d'usuari l'ha de fer manualment l'Administrador del lloc. Generalment pot trigar entre pocs minuts i 24 hores.";

$faqlist["FAQ_022_head"] = "PERQUÈ EM CAL ENREGISTRAR-ME?";
$faqlist["FAQ_022_body"] = "Solament els usuaris enregistrats poden veure noms de persones vives. Si no esteu enregistrat us apareixerà \"Privat\" en lloc dels noms de la gent viva.";

$faqlist["FAQ_025_head"] = "QUAN DE TEMPS TARDA TENIR APROVAT EL MEU ENRGISTRAMENT?";
$faqlist["FAQ_025_body"] = "L'autorització de un nou compte d'usuari l'ha de fer manualment l'Administrador del lloc. Generalment pot trigar entre pocs minuts i 24 hores.";

$faqlist["FAQ_027_head"] = "JO ESTIC ENREGISTRAT I HE SIGUT AUTORITZAT. PUC VEURE NOMS DE GENT VIVA PERÒ NO ALGUNS DELS SEUS DETALLS.";
$faqlist["FAQ_027_body"] = "Per veure detalls (solament de les vostres branques properes), us cal formar part de l'arbre familiar i n'heu d'informar a l'Administrador del lloc/Responsable de qüestions genealògiques per correu electrònic.";

$faqlist["FAQ_030_head"] = "COM PUC ENTRAR DADES? QUINS FORMATS HE DE FER SERVIR?";
$faqlist["FAQ_030_body"] = "Heus aquí algunes indicacions:";
$faqlist["FAQ_030_body2"] = " per usuaris autoritzats a EDITAR en línea.";
$faqlist["FAQ_030_body3"] = "També podeu enviar les actualitzacions per correu electrònic.";
$faqlist["FAQ_030_HELP"] = "<strong>AJUDA</strong>: Al lloc web es dóna ajuda a bastament, a cada capçalera de pàgina i amb el símbol \"?\" al costat de la majoria d'enllaços i ítems. Si malgrat tot encara teniu dubtes, simplement demaneu-nos-ho per correu electrònic.";
$faqlist["FAQ_030_DATES"] = "<strong>DATES</strong>: Fem servir el format estàndard GEDCOM v5.5. DD MMM YYYY or 01 JAN 1822 en lloc de January 1, 1822 o Jan 1, 1822.  El sistema pot fer algunes petites correccions d'erros d'entrada, però no heu de refiar-vos-en.";
$faqlist["FAQ_030_HDATES"] = "<strong>DATES HEBREES</strong> s'omplen amb el format @#DHEBREW@ DD MMM YYYY o @#DHEBREW@ 21 AAV 5705 - Els mesos s'omplen com TSH, CSH, KSL, TVT, SHV, ADR, ADS, NSN, IYR, SVN, TMZ, AAV i ELL tal com l'estàndard GEDCOM v5.5.";
$faqlist["FAQ_030_PLACES"] = "<strong>LLOC</strong>: Sempre que la coneguem inclourem la descripció completa del lloc: ciutat i/o municipi així com Comtat, Estat i normalment afegirem USA (preferible a US, U.S., o U.S.A.) al costat de l'Estat.  Per a països estrangers podem emprar l'abreujament estàndard de 3 lletres aprovat per al GEDCOM en lloc del nom del país: Anglaterra [ENG], Escòcia [SCT], Irlanda [IRE], França [FRA], Itàlia [ITA], Catalunya [CAT] etc. El format que preferim és: <i>Indianapolis, Center Twp, Marion Co, Indiana, USA</i>  No s'han d'abreviar els Estats a dues lletres; no farem servir generalment punts (.) als noms de llocs, així <i>Shelbyville, Addison Twp, Shelby Co, Indiana, USA</i> per comptes de <i>Shelbyville, Addison Twp., Shelby Co., IN</i> or <i>Shelbyville, Addison Township, Shelby County, Indiana, U.S.A.</i>";
$faqlist["FAQ_030_PLACES2"] = "<strong>LLOCS</strong>: Intentem, si es coneix, incloure per als llocs dels Estat Units el nom complet: la població o municipi, així com el codi de dues lletres de l'estat i hi afegim USA (forma preferida - no US, U.S. o U.S.A.) darrera de l'estat.  Per a altres països fem servir la població i/o el municipi i el nom de paísara otros países, usamos la localidad o municipio u el nombre del país. Els formats preferibles son: <i>Indianapolis, IN, USA</i> i <i>Vilnius, Lithuania</i>.";
$faqlist["FAQ_030_PLACES3"] = "Hi ha dues formes útils d'esbrinar el format correcte per a un lloc:<br /><ul><li>emprar la icona petita del món del costat del camp del lloc per a veure quins llocs ja son a la base de dades. Aquesta és una bona forma de localitzar el comtat d'una localitat si no el coneixeu, dons probablement ja existeixi a les nostres dades.Feu servir el filtre per a afinar la recerca i polseu el resultat desitjat que resultarà copiat al camp buit del lloc,</li><li>polseu el signe + sota del camo de lloc. Veureu una sèrie de camps addicionals per al país, l'estat o província, el comtat i la població. Al costat del camp de país surt una llista desplegable de països amb llurs codis estàndard de tres lletres.</li></ul>";
$faqlist["FAQ_030_PLACES4"] = "Hi ha dues formes útils d'esbrinar el format correcte per a un lloc:<br /><ul><li>emprar la icona petita del món del costat del camp del lloc per a veure quins llocs ja son a la base de dades. Aquesta és una bona forma de localitzar el comtat d'una localitat si no el coneixeu, dons probablement ja existeixi a les nostres dades.Feu servir el filtre per a afinar la recerca i polseu el resultat desitjat que resultarà copiat al camp buit del lloc,</li><li>polseu el signe + sota del camo de lloc. Veureu una sèrie de camps addicionals per al país, l'estat o província, el comtat (N/A) i la població. Al costat del camp de país surt una llista desplegable de països amb llurs codis estàndard de tres lletres.</li></ul>";
$faqlist["FAQ_030_PLACES5"] = "El camp \"Hebreu\" sota les dades de \"Lloc\" us permet entrar el nom del lloc en hebreu a més del nom en caràcters llatins.";
$faqlist["FAQ_030_NAMES"] = "<strong>NOMS</strong>: La introducció de noms és molt senzilla mitjançant el formulari i l'ajuda que s'ofereix. Normalment el formulari d'entrada de persones ja mostrarà camps separats per a cada part del nom. Si no apareguessin, polseu el signe + corresponent.";
$faqlist["FAQ_030_PREFIX"] = "<u>PREFIXOS</u> es refereixen a prefixos del nom i son generalment tractaments com Dr.,Excm. Sr., Il·lm. Sr., etc.  Tractaments ordinaris com Sr., Sra., etc. és preferible no inclourel's.";
$faqlist["FAQ_030_GIVN"] = "<u>GIVN</u> - Els noms de pila son els primers i els d'entremig habitualment son escollits al naixement.";
$faqlist["FAQ_030_GIVN1"] = " Si el nom canvia desprès del naixement, aquests noms addicionals poden afegir-se per separat desprès de que la persona hagi sigut enregistrada a la base de dades. També poden introduïr-se com a noms AKA (àlies).<br /><br />Normalment esperem que a les persones se les anomeni pel primer dels seus noms de pila. Si no és el cas, convé que indiqueu quin dels noms de pila és el preferit posant-hi un asterisc al darrera. Per exemple, <i>John James Mitchell* Jones</i> indica que aquesta persona és coneguda com \"Mitchell\".  En aquest cas, \"Mitchell\" no és un àlies, malgrat que \"Mitch\" podria ser-ho.";
$faqlist["FAQ_030_GIVN2"] = "Introduïm el nom de pila amb una majúscula inicial. La resta del nom ha d'anar en minúscules.";
$faqlist["FAQ_030_SURNAME"] = "<u>COGNOM</u> és el nom de la família. És el <u>nom de naixement</u> per a una persona casada i no pas el que reb després de l'enllaç. Mireu-vos <i>nom de casada</i> més endavant. Si hi ha canvis de nom posteriors al naixement, aquests noms addicionals poden introduïr-se per separat un cop la persona ja ha estat enregistrada a la base de dades. També poden afegir-se com a noms AKA (àlies).";
$faqlist["FAQ_030_SURNAME2"] = " Cal entrar el COGNOM començant-lo amb una lletra majúscula. La resta de lletres han d'anar en minúscules.";
$faqlist["FAQ_030_SUFFIX"] = "El <u>SUFFIX</u> conté suffixos del nom com ara Jr, Sr, III, etc.";
$faqlist["FAQ_030_NICKNAME"] = "<u>ÀLIES</u> és el nom emprat habitualment per la persona si és diferent de llur nom de pila. Per exemple, <i>Jack</i> podría ésser l'àlies de John \"Jack\" Arnold, Daniel Wilson tenia como a àlies <i>Tuggy</i> i moltes Margarets tenen com a àlies <i>Maggie, Nancy, Peggy, Polly</i>, etc.";
$faqlist["FAQ_030_HEBNAME"] = "<u>NOM HEBREU</u> és la traducció hebrea del nom de la persona en caràcters llatins. Ningú pot tenir més d'un nom hebreu. PhpGedView espera que es tanqui el cognom entre barres. El nom &#1497;&#1506;&#1511;&#1489; &#1500;&#1493;&#1497; s'introduirà com &#1497;&#1506;&#1511;&#1489; /&#1500;&#1493;&#1497;/.";
$faqlist["FAQ_030_AKANAME"] = "<u>NOM ÀLIES</u> és un nom addicional pel que es coneix a una persona. Podria ésser el nom de naixement de persones que l'hagin canviat posteriorment, un àlies, un pseudònim o un nom artístic. Podria ésser també un nom de casada. El nom de pila introduït aquí pot ésser diferent del nom de pila principal. PhpGedView espera que tanqueu el cognom entre barres. El nom <i>James Adams</i> s'ha d'introduïr com  <i>James /Adams/</i>.";
$faqlist["FAQ_030_AKANAME2"] = " Els noms addicionals hebreus o Yiddish també s'enregistren com a NOMS ÀLIES.";
$faqlist["FAQ_030_MARRNAME"] = "<u>NOM DE CASADA</u> és el nom que adquireix una persona quan adopta el cognom del cònjuge. El programa els crea automàticament en introduir el nou cognom al camp Nom de Casada. Per exemple <i>Mary Jane Smith</i> es casa amb <i>John Jones</i> i es converteix en  <i>Mary Jane Jones</i> si introduïu <i>Jones</i> al camp de Cognom de Casada. Els noms de casada no son exclusius de les dones; podeu introduir un nom de casada per a persones de qualsevol gènere.";
$faqlist["FAQ_030_MARRNAME2"] = "Els noms de casada hebreus adquireixen el nom de pila del nom de pila hebreu.";
$faqlist["FAQ_030_NAMES2"] = "L'opció <i>Modificar nom</i> que apareix ocasionalment sota el nom d'una persona a la pàgina de detalls personals, us permet modificar qualsevol aspecte del nom d'aquesta persona. L'opció <i>Esliminar nom</i>, també sota el nom de la persona us permet eliminar el nom de la informació de la persona sense eliminar o canviar res més. Podeu modificar i afegir altres noms a la informació de la persona polsant sobre les opcions  <i>Modificar nom</i> o <i>Afegir un nou nom</i> al sotsmenú <i>Editar</i> del menú <i>Opcions per la persona</i>. Es pot obtenir més informació polsant la icona d'ajuda associada a aquestes opcions.";
$faqlist["FAQ_030_SOURC"] = "<strong>FONTS</strong> i <strong>CITACIONS</strong>: En genealogia, no n'hi ha prou amb dir que quelcom  \"ocorreguè en tal data\". Els historiadors volen proves. Nosaltres també!. Si us plau, proporcioneu qualsevol mena d'informació que tingueu sobre la font de la informació que esteu proporcionant. Comproveu les diferents maneres d'introduir informació de les fonts i empreu l'opció de NOTES si teniu dubtes o si us cal més espai per encabir-la. Poseu-hi més del que us sembli necessari, mai serà massa. Teniu preguntes? Pregunteu el que no entengueu i estarem encantats d'ajudar-vos.";
$faqlist["FAQ_030_CHNG"] = "<strong>CANVIS</strong> i <strong>ENTRADES</strong>: Els canvis de dades existents d'una persona o família no apareixeran fins que hagin sigut aprovats per un administrador. Malgrat que repassem sovint el lloc, envieu-nos un correu electrònic si voleu que revisem i autoritzem les modificacions més ràpidament. Els esdeveniments relatius a la creació o modificació d'una unitat familiar s'introdueixen a la pàgina de parents propers o a la de la família. Aquí es on heu d'enregistrar casaments, divorcis, mainada, censos familiars; qualsevol fet o esdeveniment que afecti a tota la unitat familiar. Ens sembla que quan cal afegir diversos fills és millor emprar l'enllaç MOSTRA LA FAMILIA d'aquest espòs/esposa i afegir cada fill mitjançant l'enllaç al peu, 'AFEGIR UN FILL/A A AQUESTA FAMÍLIA'.  És més ràpid que fer servir la pàgina de parents propers dons, desprès de cada acció, retrona a la pàgina de la persona per comptes de la de parents propers. ¿Teniu dubtes? Pregunteu el que no entengueu i estarem encantats d'ajudar-vos.";
$faqlist["FAQ_030_MEDIA"] = "<strong>OBJECTES</strong>: Agraïm molt que aporteu fotografies, partides de bateig, llicències i partides matrrimonials, partides de defunció,... qualsevol cosa que tingueu com a suport documental. És fàcil afegir-les des del vostre disc dur emprant la pestanya OBJECTES, l'enllaç AFEGIR MULTIMÈDIA i l'eina CARREGAR/PUJAR del navegador.  També, si tieniu dubtes, suggeriments o us cal ajuda, envieu-nos les vostres imatges digitalitzades per correu electrònic i nosaltres ens encarregarem d'afegir-les";
$faqlist["FAQ_030_MEDIA2"] = "En introduïr nous objectes, considereu la possibilitat d'establir un conveni de noms que no produeixi sovint conflictes amb altres objectes. El sistema us permet examinar el vostre disc i pujar documents amb un nom completament diferent sense afectar el vostre arxiu local. Imagineu-vos quants arxius \"joan.jpg\" pot haver-hi (bé, solament pot haver-n'hi un) però podrieu sobreescriure un arxiu preexistent si no li canvieu el nom. Preferim els noms d'arxiu curts (menys de 35 caràcters) però descriptius com ara J_Nom-b1820-I23445.jpg o K_Nom-I23444-Headstn.jpg. En cas de dubte, consulteu-nos.";
$faqlist["FAQ_030_NAVIGATE"] = "<strong>NAVEGACIÓ</strong>: Naveguem emprant el DIAGRAMA DE CERCLE i els d'avantpassats i descendents. Proveu-los. Recordeu que moltes funcions no rutllen si no teniu la vostra pàgina personal vinculada amb els vostres avantpassats.";

$faqlist["FAQ_032_head"] = "PUC AFEGIR/MODIFICAR LES DADES DE QUALSEVOL PERSONA DE L'ARBRE?";
$faqlist["FAQ_032_body"] = "Sí.<br />Però heu de formar part de l'arbre i estar autoritzat per a fer modificacions. Solament podeu fer canvis o afegir a les vostres rames properes. També podeu proposar-nos canvis enviant-los per correu electrònic.";

$faqlist["FAQ_037_head"] = "HE TINGUT PROBLEMES MODIFICANT L'ARBRE. QUÈ EM CAL FER?";
$faqlist["FAQ_037_body"] = "Podeu enviar aquests canvis per correu electrònic a l'administrador  <br />a l'adreça: #GLOBALS[Webmaster_EMAIL]#";
$faqlist["FAQ_037_body2"] = "Puede enviar sus cambios por correo electrónico al administrador<br />en: #GLOBALS[CONTACT_EMAIL]#";

$faqlist["FAQ_040_head"] = "I QUÈ HI HA DE LA PRIVADESA?";
$faqlist["FAQ_040_body"] = "<b>#GLOBALS[GEDCOM_TITLE]# creu que la protecció de la informació personal és molt important</b>. Les funcions de privadesa del programa PhpGedView son excel·lents per a l'establiment d'algunes regles de privadesa. En general el nostre lloc amaga els detalls de persones vives o d'aquelles amb les que no hi esteu emparentat. Per veure detalls de les persones vives us caldrà accedir al sistema mitjançant un nom d'usuari i una contrasenya. Aquesta identificació va vinculada amb el vostre lloc a l'arbre familiar. El nostre lloc web també fa servir la funció  \"privadesa de perentiu\" de PhpGedView. Aquesta característica us permet veure únicament informació de persones dofinides com a parents propers. Si us heu identificat i veieu que algunes persones entan marcades com a  \"Informació provada\", vol dir que hi ha activada aquesta característica.  Si penseu que el vostre accès és massa limitat, envieu un missatge electrònic a l'administrador del lloc i indicant els número d'ID de les persones a les que voleu accedir i els motius pels que voleu fer-ho.";
$faqlist["FAQ_040_body2"] = "Per descomptat que cap sistema és perfecte o inviolable, així que la possibilitat d'un accés no desitjat a les dades, és possible. Fem tot el que podem per solucionar els problemes de privadesa ràpidament. Si teniu serioses objeccions a que algunes de les vostres dades personals apareixin aquí, contacteu amb l'administrador mitjançant l'enllaç al formulari que surt a la part inferior. Els vostres detalls poden eliminar-se del lloc, malgrat que el vostre accés també pot resultar limitat. Mireu-vos la 'pregunta freqüent' sobre quina informació s'emmagatzema en aquest lloc.<br /><br /><b>Ens prenem seriosament l'abús de la informació i el robatori o el mal ús que se'n pugui fer i actuarem contra els que participin o intentin un robatori d'identitat basat en les dades d'aquest lloc. NO copieu les nostres dades sobre persones vives a altres llocs que podrien no protegir-les apropiadament dons podrieu resultar responsable dels possibles perjudicis..</b>";

$faqlist["FAQ_050_head"] = "AGRAÏMENT";
$faqlist["FAQ_050_body"] = "L'adquisició i manteniment d'aquest volum d'informació no seria possible sense l'ajuda i participació de molts parents. La genealogia és molt divertida i una experiència d'aprenentatge meravellosa. ampliant tant el nostre coneixement de la família com el coneixement en general de la geografia i la sociologia. Esperem que ho disfruteu tant com nosaltres i ens entusiasma la nostra futura cooperació mútua i l'amistat establerta mitjançant les funcions de PhpGedView i el nostre lloc web #GLOBALS[GEDCOM_TITLE]#.<br /><br />No dubteu en enviar-nos un missatge per saludar, avisar-nos d'alguna esmena o addició necessària o per a preguntar sobre algun parentiu. La majoria del que coneixem resta a la vista, solament s'amaguen els detalls de parents vius .<br /><br />Gràcies de nou.";

?>
